// deno-fmt-ignore-file
// deno-lint-ignore-file
// This code was bundled using `deno bundle` and it's not recommended to edit it manually

const capitalize = (s = "s", titlecase = false)=>s.charAt(0).toUpperCase() + `${titlecase ? s.slice(1).toLowerCase() : s.slice(1)}`;
const getRandom = (arr)=>Array.isArray(arr) ? arr[Math.floor(Math.random() * arr.length)] : arr;
const reverseString = (str)=>str.split("").reverse().join();
export { capitalize as capitalize };
export { getRandom as getRandom };
export { reverseString as reverseString };
const __default = [
    "accurate",
    "adventurous",
    "aggressive",
    "agoraphobic",
    "alien",
    "alpha",
    "amazing",
    "amphibious",
    "ancient",
    "angelic",
    "average",
    "avian",
    "awesome",
    "bad",
    "beefy",
    "belligerent",
    "betrayed",
    "bipedal",
    "bitter",
    "black",
    "blind",
    "boisterous",
    "brilliant",
    "bronze",
    "canine",
    "certified",
    "charitable",
    "charming",
    "cheeky",
    "cheerful",
    "childish",
    "chivalrous",
    "clever",
    "clueless",
    "clumsy",
    "comical",
    "complex",
    "confident",
    "cool",
    "crybaby",
    "cuddly",
    "cunning",
    "curious",
    "cute",
    "dangerous",
    "dark",
    "decent",
    "delicious",
    "delusional",
    "dense",
    "desperate",
    "diabetic",
    "divine",
    "dominant",
    "dragon",
    "dramatic",
    "drunk",
    "dwarven",
    "eerie",
    "egghead",
    "electric",
    "elegant",
    "elemental",
    "elven",
    "enchanting",
    "faithful",
    "famous",
    "fantastic",
    "feline",
    "female",
    "feminine",
    "friendly",
    "funny",
    "gallant",
    "gay",
    "generous",
    "gentle",
    "geographic",
    "giant",
    "godlike",
    "gold",
    "good",
    "grand",
    "great",
    "gruesome",
    "gullible",
    "harsh",
    "high",
    "holy",
    "hostile",
    "humble",
    "hypersonic",
    "idiotic",
    "immortal",
    "inferior",
    "innocent",
    "invincible",
    "iron",
    "jazzy",
    "jinxed",
    "jittery",
    "kidney-shaped",
    "kindhearted",
    "lackadaisical",
    "lackluster",
    "large",
    "lawful",
    "legendary",
    "lemon-like",
    "listless",
    "lively",
    "lowly",
    "malnourished",
    "masculine",
    "massive",
    "matchless",
    "meek",
    "melancholic",
    "merciless",
    "mindless",
    "monstrous",
    "mythical",
    "naive",
    "naked",
    "nerdy",
    "noble",
    "nocturnal",
    "notorious",
    "novel",
    "nutty",
    "obsessive",
    "omnipotent",
    "omniscient",
    "optimistic",
    "outstanding",
    "overpowered",
    "overweight",
    "peaceful",
    "pessimistic",
    "popular",
    "powerful",
    "powerless",
    "pretty",
    "proud",
    "pure",
    "rabid",
    "reincarnated",
    "reinstated",
    "repugnant",
    "repulsive",
    "rich",
    "rotten",
    "round",
    "rowdy",
    "royal",
    "rude",
    "rugged",
    "ruthless",
    "sacred",
    "sassy",
    "selfish",
    "selfless",
    "shiny",
    "short",
    "silver",
    "skinny",
    "slender",
    "slick",
    "slim",
    "slimy",
    "sly",
    "spirit",
    "steel",
    "stereotypical",
    "strong",
    "successful",
    "summoned",
    "super",
    "sweet",
    "talkative",
    "tall",
    "tender",
    "timid",
    "tiny",
    "trashy",
    "tyrannical",
    "ultimate",
    "underweight",
    "unmatched",
    "upbeat",
    "valiant",
    "verbose",
    "villainous",
    "viscous",
    "voracious",
    "war-crazed",
    "warlord",
    "weak",
    "weary",
    "wheezy",
    "whiny",
    "wholesome",
    "wicked",
    "wise",
    "witty",
    "world-class",
    "xenophobic",
    "young",
    "zazzy",
    "zen", 
];
const __default1 = {
    fight: [
        "attack",
        "battle",
        "brawl",
        "challenge",
        "combat",
        "counter",
        "duel",
        "fight",
        "joust", 
    ],
    death: [
        "died",
        "got killed",
        "ended up dying",
        "passed away",
        "lost my life", 
    ],
    intro: [
        "I am",
        "My name is",
        "I'm",
        "I am called",
        "I was known as",
        "I used to be called",
        "I was once called",
        "When I was alive, they called me",
        "Once upon a time, I was called",
        "I think my name was",
        "I am not sure if my name was", 
    ],
    join: [
        "band together",
        "join hands",
        "compete with each other",
        "form an alliance",
        "declare their love to each other",
        "become sworn siblings",
        "pledge their souls",
        "form a truce",
        "become allies",
        "forget their differences", 
    ],
    actions: {
        singular: [
            "defend against",
            "negotiate with",
            "hold out against",
            "run from",
            "survive", 
        ],
        plural: [
            "defends against",
            "negotiates with",
            "holds out against",
            "runs from",
            "strives to survive", 
        ]
    },
    forward: [
        "forward",
        "send",
        "show",
        "copy/paste"
    ],
    message: [
        "message",
        "story",
        "text"
    ],
    level: [
        "level",
        "lv",
        "lvl",
        "tier",
        "stage",
        "rank",
        "class"
    ]
};
const __default2 = [
    0,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    20,
    30,
    40,
    50,
    60,
    69,
    70,
    80,
    90,
    99,
    100,
    101,
    200,
    420,
    500,
    666,
    999,
    1000,
    6969,
    9999,
    10000,
    42069,
    69420,
    99999,
    100000,
    1000000, 
];
const __default3 = [
    "hero",
    "mage",
    "wizard",
    "sage",
    "monk",
    "NEET",
    "dragon",
    "hunter",
    "salesman",
    "salaryman",
    "digital artist",
    "weeb",
    "artist",
    "gacha gamer",
    "game developer",
    "Florida man",
    "pokemon master",
    "narcissist",
    "programmer",
    "web developer",
    "yankee",
    "yakuza",
    "ying-yang master",
    "taoist",
    "archangel",
    "baiter",
    "investigator",
    "king",
    "magician",
    "eggman",
    "lancer",
    "archer",
    "berserker",
    "rider",
    "athlete",
    "master",
    "martial artist",
    "demon",
    "god",
    "zombie",
    "skeleton",
    "vampire",
    "undead",
    "lich",
    "golem",
    "swordsman",
    "sword saint",
    "shielder",
    "spearmaster",
    "gunslinger",
    "cowboy",
    "karen",
    "tomboy",
    "femboy",
    "gal",
    "nerd", 
];
const generateCharacter = ()=>{
    return `${Math.random() < 0.9 ? Math.random() > 0.3 ? `${getRandom(__default)} ` : `${getRandom(__default1.level)} ${getRandom(__default2)} ` : ""}${getRandom(__default3)}`;
};
const vowels = [
    "A",
    "E",
    "I",
    "O",
    "U"
];
const alphabet = [
    "A",
    "B",
    "C",
    "D",
    "E",
    "F",
    "G",
    "H",
    "I",
    "J",
    "K",
    "L",
    "M",
    "N",
    "O",
    "P",
    "Q",
    "R",
    "S",
    "T",
    "U",
    "V",
    "W",
    "X",
    "Y",
    "Z", 
];
const consonants = alphabet.filter((x)=>!vowels.includes(x));
const __default4 = [
    {
        letter: "A",
        possible: [
            "A",
            "B",
            "C",
            "D",
            "E",
            "F",
            "G",
            "H",
            "I",
            "J",
            "K",
            "L",
            "M",
            "N",
            "O",
            "P",
            "Q",
            "R",
            "S",
            "T",
            "U",
            "V",
            "W",
            "X",
            "Y",
            "Z", 
        ]
    },
    {
        letter: "B",
        possible: [
            "A",
            "E",
            "I",
            "O",
            "U",
            "H",
            "Y",
            "R",
            "W", 
        ]
    },
    {
        letter: "C",
        possible: [
            "A",
            "E",
            "I",
            "O",
            "U",
            "H",
            "Y",
            "R",
            "W", 
        ]
    },
    {
        letter: "D",
        possible: [
            "A",
            "E",
            "I",
            "O",
            "U",
            "H",
            "Y",
            "R",
            "W", 
        ]
    },
    {
        letter: "E",
        possible: [
            "A",
            "B",
            "C",
            "D",
            "E",
            "F",
            "G",
            "H",
            "I",
            "J",
            "K",
            "L",
            "M",
            "N",
            "O",
            "P",
            "Q",
            "R",
            "S",
            "T",
            "U",
            "V",
            "W",
            "X",
            "Y",
            "Z", 
        ]
    },
    {
        letter: "F",
        possible: [
            "A",
            "E",
            "I",
            "O",
            "U",
            "H",
            "Y",
            "R",
            "W", 
        ]
    },
    {
        letter: "G",
        possible: [
            "A",
            "E",
            "I",
            "O",
            "U",
            "H",
            "Y",
            "R",
            "W", 
        ]
    },
    {
        letter: "H",
        possible: [
            "A",
            "E",
            "I",
            "O",
            "U",
            "Y",
            "W", 
        ]
    },
    {
        letter: "I",
        possible: [
            "A",
            "B",
            "C",
            "D",
            "E",
            "F",
            "G",
            "H",
            "I",
            "J",
            "K",
            "L",
            "M",
            "N",
            "O",
            "P",
            "Q",
            "R",
            "S",
            "T",
            "U",
            "V",
            "W",
            "X",
            "Y",
            "Z", 
        ]
    },
    {
        letter: "J",
        possible: [
            "A",
            "E",
            "I",
            "O",
            "U",
            "H",
            "Y", 
        ]
    },
    {
        letter: "K",
        possible: [
            "A",
            "E",
            "I",
            "O",
            "U",
            "H",
            "Y",
            "R",
            "W", 
        ]
    },
    {
        letter: "L",
        possible: [
            "A",
            "E",
            "I",
            "O",
            "U",
            "Y"
        ]
    },
    {
        letter: "M",
        possible: [
            "A",
            "E",
            "I",
            "O",
            "U",
            "H",
            "Y", 
        ]
    },
    {
        letter: "N",
        possible: [
            "A",
            "E",
            "I",
            "O",
            "U",
            "H",
            "Y",
            "W", 
        ]
    },
    {
        letter: "O",
        possible: [
            "A",
            "B",
            "C",
            "D",
            "E",
            "F",
            "G",
            "H",
            "I",
            "J",
            "K",
            "L",
            "M",
            "N",
            "O",
            "P",
            "Q",
            "R",
            "S",
            "T",
            "U",
            "V",
            "W",
            "X",
            "Y",
            "Z", 
        ]
    },
    {
        letter: "P",
        possible: [
            "A",
            "E",
            "I",
            "O",
            "U",
            "H",
            "Y",
            "R",
            "S",
            "W", 
        ]
    },
    {
        letter: "Q",
        possible: [
            "A",
            "E",
            "I",
            "O",
            "U"
        ]
    },
    {
        letter: "R",
        possible: [
            "A",
            "E",
            "I",
            "O",
            "U",
            "H",
            "Y",
            "W", 
        ]
    },
    {
        letter: "S",
        possible: [
            "A",
            "B",
            "C",
            "D",
            "E",
            "F",
            "G",
            "H",
            "I",
            "J",
            "K",
            "L",
            "M",
            "N",
            "O",
            "P",
            "Q",
            "R",
            "S",
            "T",
            "U",
            "V",
            "W",
            "X",
            "Y",
            "Z", 
        ]
    },
    {
        letter: "T",
        possible: [
            "A",
            "E",
            "I",
            "O",
            "U",
            "H",
            "Y",
            "R",
            "S",
            "W", 
        ]
    },
    {
        letter: "U",
        possible: [
            "A",
            "B",
            "C",
            "D",
            "E",
            "F",
            "G",
            "H",
            "I",
            "J",
            "K",
            "L",
            "M",
            "N",
            "O",
            "P",
            "Q",
            "R",
            "S",
            "T",
            "U",
            "V",
            "W",
            "X",
            "Y",
            "Z", 
        ]
    },
    {
        letter: "V",
        possible: [
            "A",
            "E",
            "I",
            "O",
            "U",
            "H",
            "Y",
            "R", 
        ]
    },
    {
        letter: "W",
        possible: [
            "A",
            "E",
            "I",
            "O",
            "U",
            "H",
            "Y",
            "R", 
        ]
    },
    {
        letter: "X",
        possible: [
            "A",
            "E",
            "I",
            "O",
            "U",
            "H"
        ]
    },
    {
        letter: "Y",
        possible: [
            "A",
            "B",
            "C",
            "D",
            "E",
            "F",
            "G",
            "H",
            "I",
            "J",
            "K",
            "L",
            "M",
            "N",
            "O",
            "P",
            "Q",
            "R",
            "S",
            "T",
            "U",
            "V",
            "W",
            "X",
            "Z", 
        ]
    },
    {
        letter: "Z",
        possible: [
            "A",
            "E",
            "I",
            "O",
            "U",
            "H"
        ]
    }, 
];
function generateName(lenn) {
    if (!lenn) lenn = 4 + Math.floor(Math.random() * 5);
    let name = getRandom(alphabet);
    for(let pointer = 0; pointer < lenn - 1; ++pointer){
        if (pointer === lenn - 2) {
            name += getRandom(__default4.find((x)=>x.letter === name.charAt(name.length - 1).toUpperCase())?.possible ?? vowels);
        } else {
            if (consonants.includes(name.charAt(name.length - 1)) && consonants.includes(name.charAt(name.length - 2))) {
                name += getRandom(vowels);
            } else if (vowels.includes(name.charAt(name.length - 1)) && vowels.includes(name.charAt(name.length - 2)) && vowels.includes(name.charAt(name.length - 3))) {
                name += getRandom(consonants);
            } else {
                name += getRandom(__default4.find((x)=>x.letter === name.charAt(name.length - 1).toUpperCase())?.possible ?? vowels);
            }
        }
    }
    return name;
}
const __default5 = [
    "er",
    "ug",
    "ugg",
    "or",
    "in",
    "ius",
    "ion",
    "xion",
    "ixie",
    "ora",
    "ra", 
];
const generateFantasyName = ()=>{
    return `${generateName(3 + Math.floor(Math.random() * 5)).toLowerCase()}${getRandom(__default5)}`;
};
const Creatures = [
    {
        name: "imp",
        plural: "imps",
        level: 2,
        affiliation: -1,
        intelligence: 3,
        size: 1,
        body_parts: {
            tail: true,
            head: true,
            wings: true,
            hands: true,
            legs: true,
            fingers: true,
            toes: true,
            horns: true,
            animal_ears: false
        },
        magical: true,
        appearance: 1
    },
    {
        name: "fairy",
        plural: "faries",
        level: 3,
        affiliation: 1,
        intelligence: 5,
        size: 1,
        body_parts: {
            tail: false,
            head: true,
            wings: true,
            hands: true,
            legs: true,
            fingers: true,
            toes: true,
            horns: false,
            animal_ears: false
        },
        magical: true,
        appearance: 6
    },
    {
        name: "dragon",
        plural: "dragons",
        level: 7,
        affiliation: 0,
        intelligence: 7,
        size: 5,
        body_parts: {
            tail: true,
            head: true,
            wings: true,
            hands: true,
            legs: true,
            fingers: true,
            toes: true,
            horns: true,
            animal_ears: true
        },
        magical: true,
        appearance: 5
    },
    {
        name: "elf",
        plural: "elves",
        level: 5,
        affiliation: 0,
        intelligence: 5,
        size: 3,
        body_parts: {
            tail: false,
            head: true,
            wings: false,
            hands: true,
            legs: true,
            fingers: true,
            toes: true,
            horns: false,
            animal_ears: true
        },
        magical: true,
        appearance: 6
    },
    {
        name: "angel",
        plural: "angels",
        level: 7,
        affiliation: 1,
        intelligence: 7,
        size: 3,
        body_parts: {
            tail: false,
            head: true,
            wings: true,
            hands: true,
            legs: true,
            fingers: true,
            toes: true,
            horns: false,
            animal_ears: false
        },
        magical: true,
        appearance: 7
    },
    {
        name: "giant",
        plural: "giants",
        level: 5,
        affiliation: 0,
        intelligence: 3,
        size: 5,
        body_parts: {
            tail: false,
            head: true,
            wings: false,
            hands: true,
            legs: true,
            fingers: true,
            toes: true,
            horns: true,
            animal_ears: false
        },
        magical: true,
        appearance: 1
    },
    {
        name: "skeleton",
        plural: "skeletons",
        level: 1,
        affiliation: -1,
        intelligence: 0,
        size: 3,
        body_parts: {
            tail: false,
            head: false,
            wings: false,
            hands: false,
            legs: false,
            fingers: false,
            toes: false,
            horns: false,
            animal_ears: false
        },
        magical: false,
        appearance: 0
    },
    {
        name: "undead",
        plural: "undead",
        level: 1,
        affiliation: -1,
        intelligence: 0,
        size: 3,
        body_parts: {
            tail: false,
            head: true,
            wings: false,
            hands: true,
            legs: true,
            fingers: true,
            toes: true,
            horns: false,
            animal_ears: false
        },
        magical: false,
        appearance: 0
    },
    {
        name: "succubus",
        plural: "succubi",
        level: 3,
        affiliation: -1,
        intelligence: 5,
        size: 3,
        body_parts: {
            tail: true,
            head: true,
            wings: true,
            hands: true,
            legs: true,
            fingers: true,
            toes: true,
            horns: true,
            animal_ears: false
        },
        magical: true,
        appearance: 6
    },
    {
        name: "incubus",
        plural: "incubi",
        level: 3,
        affiliation: -1,
        intelligence: 5,
        size: 3,
        body_parts: {
            tail: true,
            head: true,
            wings: true,
            hands: true,
            legs: true,
            fingers: true,
            toes: true,
            horns: true,
            animal_ears: false
        },
        magical: true,
        appearance: 6
    },
    {
        name: "demon",
        plural: "demons",
        level: 3,
        affiliation: -1,
        intelligence: 3,
        size: 3,
        body_parts: {
            tail: true,
            head: true,
            wings: true,
            hands: true,
            legs: true,
            fingers: true,
            toes: true,
            horns: true,
            animal_ears: true
        },
        magical: true,
        appearance: 3
    },
    {
        name: "slime",
        plural: "slimes",
        level: 1,
        affiliation: -1,
        intelligence: 3,
        size: 1,
        body_parts: {
            tail: true,
            head: true,
            wings: true,
            hands: true,
            legs: true,
            fingers: true,
            toes: true,
            horns: true,
            animal_ears: true
        },
        magical: true,
        appearance: 0
    },
    {
        name: "wisp",
        plural: "wisps",
        level: 1,
        affiliation: 0,
        intelligence: 0,
        size: 1,
        body_parts: {
            tail: false,
            head: false,
            wings: false,
            hands: false,
            legs: false,
            fingers: false,
            toes: false,
            horns: false,
            animal_ears: false
        },
        magical: true,
        appearance: 0
    },
    {
        name: "harpy",
        plural: "harpies",
        level: 1,
        affiliation: 0,
        intelligence: 3,
        size: 3,
        body_parts: {
            tail: true,
            head: true,
            wings: true,
            hands: false,
            legs: true,
            fingers: false,
            toes: true,
            horns: false,
            animal_ears: false
        },
        magical: false,
        appearance: 3
    },
    {
        name: "bat",
        plural: "bats",
        level: 1,
        affiliation: 0,
        intelligence: 1,
        size: 1,
        body_parts: {
            tail: true,
            head: true,
            wings: true,
            hands: false,
            legs: true,
            fingers: false,
            toes: true,
            horns: false,
            animal_ears: true
        },
        magical: false,
        appearance: 1
    },
    {
        name: "orc",
        plural: "orcs",
        level: 3,
        affiliation: -1,
        intelligence: 3,
        size: 4,
        body_parts: {
            tail: true,
            head: true,
            wings: false,
            hands: true,
            legs: true,
            fingers: true,
            toes: true,
            horns: true,
            animal_ears: true
        },
        magical: false,
        appearance: 1
    },
    {
        name: "goblin",
        plural: "goblins",
        level: 1,
        affiliation: -1,
        intelligence: 3,
        size: 1,
        body_parts: {
            tail: false,
            head: true,
            wings: false,
            hands: true,
            legs: true,
            fingers: true,
            toes: true,
            horns: false,
            animal_ears: false
        },
        magical: false,
        appearance: 1
    },
    {
        name: "kobold",
        plural: "kobolds",
        level: 5,
        affiliation: 0,
        intelligence: 3,
        size: 4,
        body_parts: {
            tail: true,
            head: true,
            wings: false,
            hands: true,
            legs: true,
            fingers: true,
            toes: true,
            horns: false,
            animal_ears: true
        },
        magical: false,
        appearance: 1
    },
    {
        name: "dark elf",
        plural: "dark elves",
        level: 5,
        affiliation: -1,
        intelligence: 5,
        size: 3,
        body_parts: {
            tail: false,
            head: true,
            wings: false,
            hands: true,
            legs: true,
            fingers: true,
            toes: true,
            horns: false,
            animal_ears: false
        },
        magical: true,
        appearance: 6
    },
    {
        name: "golem",
        plural: "golems",
        level: 5,
        affiliation: 0,
        intelligence: 1,
        size: 0,
        body_parts: {
            tail: true,
            head: true,
            wings: false,
            hands: true,
            legs: true,
            fingers: true,
            toes: true,
            horns: true,
            animal_ears: false
        },
        magical: true,
        appearance: 0
    },
    {
        name: "dragonewt",
        plural: "dragonewts",
        level: 5,
        affiliation: 0,
        intelligence: 5,
        size: 3,
        body_parts: {
            tail: true,
            head: true,
            wings: true,
            hands: true,
            legs: true,
            fingers: true,
            toes: true,
            horns: true,
            animal_ears: true
        },
        magical: false,
        appearance: 5
    },
    {
        name: "sandworm",
        plural: "sandworms",
        level: 6,
        affiliation: -1,
        intelligence: 0,
        size: 5,
        body_parts: {
            tail: false,
            head: false,
            wings: false,
            hands: false,
            legs: false,
            fingers: false,
            toes: false,
            horns: false,
            animal_ears: false
        },
        magical: false,
        appearance: 1
    },
    {
        name: "werewolf",
        plural: "werewolves",
        level: 3,
        affiliation: 0,
        intelligence: 3,
        size: 4,
        body_parts: {
            tail: true,
            head: true,
            wings: false,
            hands: true,
            legs: true,
            fingers: true,
            toes: true,
            horns: false,
            animal_ears: true
        },
        magical: false,
        appearance: 3
    },
    {
        name: "vampire",
        plural: "vampires",
        level: 5,
        affiliation: -1,
        intelligence: 5,
        size: 3,
        body_parts: {
            tail: false,
            head: true,
            wings: true,
            hands: true,
            legs: true,
            fingers: true,
            toes: true,
            horns: false,
            animal_ears: false
        },
        magical: false,
        appearance: 5
    },
    {
        name: "lamia",
        plural: "lamia",
        level: 1,
        affiliation: -1,
        intelligence: 3,
        size: 3,
        body_parts: {
            tail: true,
            head: true,
            wings: false,
            hands: true,
            legs: false,
            fingers: true,
            toes: false,
            horns: false,
            animal_ears: false
        },
        magical: false,
        appearance: 5
    },
    {
        name: "ogre",
        plural: "ogres",
        level: 3,
        affiliation: -1,
        intelligence: 3,
        size: 4,
        body_parts: {
            tail: false,
            head: true,
            wings: false,
            hands: true,
            legs: true,
            fingers: true,
            toes: true,
            horns: true,
            animal_ears: false
        },
        magical: false,
        appearance: 1
    },
    {
        name: "oni",
        plural: "oni",
        level: 3,
        affiliation: -1,
        intelligence: 3,
        size: 4,
        body_parts: {
            tail: false,
            head: true,
            wings: false,
            hands: true,
            legs: true,
            fingers: true,
            toes: true,
            horns: true,
            animal_ears: false
        },
        magical: false,
        appearance: 1
    },
    {
        name: "siren",
        plural: "sirens",
        level: 3,
        affiliation: -1,
        intelligence: 3,
        size: 3,
        body_parts: {
            tail: true,
            head: true,
            wings: false,
            hands: true,
            legs: false,
            fingers: true,
            toes: true,
            horns: false,
            animal_ears: false
        },
        magical: true,
        appearance: 5
    },
    {
        name: "griffon",
        plural: "griffons",
        level: 5,
        affiliation: 1,
        intelligence: 5,
        size: 4,
        body_parts: {
            tail: true,
            head: true,
            wings: true,
            hands: true,
            legs: true,
            fingers: true,
            toes: true,
            horns: true,
            animal_ears: true
        },
        magical: false,
        appearance: 5
    },
    {
        name: "manticore",
        plural: "manticores",
        level: 5,
        affiliation: -1,
        intelligence: 3,
        size: 4,
        body_parts: {
            tail: true,
            head: true,
            wings: true,
            hands: true,
            legs: true,
            fingers: true,
            toes: true,
            horns: true,
            animal_ears: true
        },
        magical: false,
        appearance: 1
    },
    {
        name: "hippogriff",
        plural: "hippogriff",
        level: 5,
        affiliation: 1,
        intelligence: 5,
        size: 4,
        body_parts: {
            tail: true,
            head: true,
            wings: true,
            hands: true,
            legs: true,
            fingers: true,
            toes: true,
            horns: true,
            animal_ears: true
        },
        magical: false,
        appearance: 1
    },
    {
        name: "drake",
        plural: "drakes",
        level: 5,
        affiliation: 0,
        intelligence: 5,
        size: 5,
        body_parts: {
            tail: true,
            head: true,
            wings: false,
            hands: true,
            legs: true,
            fingers: true,
            toes: true,
            horns: true,
            animal_ears: true
        },
        magical: true,
        appearance: 5
    },
    {
        name: "wyvern",
        plural: "wyverns",
        level: 3,
        affiliation: -1,
        intelligence: 1,
        size: 4,
        body_parts: {
            tail: true,
            head: true,
            wings: true,
            hands: false,
            legs: false,
            fingers: false,
            toes: false,
            horns: true,
            animal_ears: true
        },
        magical: false,
        appearance: 1
    },
    {
        name: "wraith",
        plural: "wraiths",
        level: 3,
        affiliation: -1,
        intelligence: 1,
        size: 3,
        body_parts: {
            tail: false,
            head: false,
            wings: false,
            hands: false,
            legs: false,
            fingers: false,
            toes: false,
            horns: false,
            animal_ears: false
        },
        magical: true,
        appearance: 1
    },
    {
        name: "gashadokuro",
        plural: "gashadokuro",
        level: 5,
        affiliation: -1,
        intelligence: 1,
        size: 5,
        body_parts: {
            tail: true,
            head: true,
            wings: false,
            hands: true,
            legs: true,
            fingers: true,
            toes: true,
            horns: false,
            animal_ears: false
        },
        magical: true,
        appearance: 1
    },
    {
        name: "lich",
        plural: "lich",
        level: 5,
        affiliation: -1,
        intelligence: 5,
        size: 3,
        body_parts: {
            tail: false,
            head: true,
            wings: false,
            hands: true,
            legs: true,
            fingers: true,
            toes: true,
            horns: false,
            animal_ears: false
        },
        magical: true,
        appearance: 1
    },
    {
        name: "monstrous mushroom",
        plural: "monstrous mushrooms",
        level: 3,
        affiliation: -1,
        intelligence: 5,
        size: 3,
        body_parts: {
            tail: false,
            head: true,
            wings: false,
            hands: true,
            legs: true,
            fingers: true,
            toes: true,
            horns: false,
            animal_ears: false
        },
        magical: false,
        appearance: 1
    },
    {
        name: "mycelium",
        plural: "mycelium",
        level: 1,
        affiliation: -1,
        intelligence: 3,
        size: 1,
        body_parts: {
            tail: false,
            head: true,
            wings: false,
            hands: false,
            legs: false,
            fingers: false,
            toes: false,
            horns: false,
            animal_ears: false
        },
        magical: false,
        appearance: 1
    }, 
];
class Race {
    name;
    body;
    affiliation;
    intelligence;
    size;
    magical;
    appearance;
    constructor(){
        const { body , similarities  } = run();
        this.name = capitalize(generateFantasyName());
        this.body = {
            tail: {},
            head: {},
            wings: {},
            hands: {},
            legs: {},
            fingers: {},
            toes: {},
            horns: {},
            animal_ears: {}
        };
        Object.keys(this.body).forEach((x)=>{
            this.body[x] = {
                exists: body[x],
                similarities: similarities[x]
            };
        });
        this.affiliation = getRandom(Creatures).affiliation;
        this.intelligence = getRandom(Creatures).intelligence;
        this.size = getRandom(Creatures).size;
        this.magical = getRandom(Creatures).magical;
        this.appearance = getRandom(Creatures).size;
    }
    get human() {
        if (this.body.head?.exists && this.body.hands?.exists && this.body.legs?.exists && this.body.fingers?.exists && this.body.toes?.exists) {
            return true;
        }
        return false;
    }
    get description() {
        return `${this.name}${this.affiliation === 0 ? ` ${getRandom([
            "is a neutral race",
            "do not take sides"
        ])}` : this.affiliation === 1 ? ` ${getRandom([
            "is a race that walks the righteous path",
            "are self-proclaimed messengers of justice",
            "is a race that proclaims to work towards the absolute good", 
        ])}` : ` ${getRandom([
            "is a chaotic race",
            "live in the darkness",
            "serve the demons", 
        ])}`}. ${this.body.head.exists ? `${getRandom([
            `Their head looks similar to that of a ${this.body.head.similarities}`,
            `They possess facial features that remind one of a ${this.body.head.similarities}`,
            `Their head is akin to that of a ${this.body.head.similarities}`, 
        ])}${this.body.animal_ears.exists ? this.body.animal_ears.similarities === this.body.head.similarities ? "" : ` but with ears that look like a ${this.body.animal_ears.similarities}` : ""}` : `${getRandom([
            "They possess no head",
            "They lack a head",
            "They are headless", 
        ])}`} and ${this.magical ? "possess a spiritual body" : `${getRandom([
            "possess a material body",
            "have a living, organic body",
            "have a normal body", 
        ])}`}. ${this.body.wings.exists ? `They possess wings that look like that of a ${this.body.wings.similarities}${Math.random() < 0.5 ? " but are actually flightless" : ""}. ` : ""}They are ${rate.size[this.size]} in size and ${rate.intelligence[this.intelligence]}. ${this.body.legs.exists ? `${getRandom([
            `Their legs look like a ${this.body.legs.similarities}'s legs`,
            `Their legs are similar to a ${this.body.legs.similarities} with small differences`, 
        ])}${!this.body.toes.exists ? " and a notable absence of toes" : ""}` : getRandom([
            "They possess no feet",
            "They lack legs"
        ])}. ${this.body.hands.exists ? this.body.legs.exists && this.body.hands.similarities === this.body.legs.similarities ? "The same could be said for their hands" : `However, they possess hands like that of a ${this.body.hands.similarities}${!this.body.fingers.exists ? "with no fingers" : ""}.` : `They possess no ${!this.body.legs.exists ? "hands either" : "modified forearms"}.`} ${this.body.horns.exists ? `They sport ${Math.random() < 0.5 ? "a wonderful horn" : `${1 + Math.ceil(Math.random() * 3)} horns`} which distantly resemble that of a ${this.body.horns.similarities}. ` : ""}On the whole, they are said to be ${rate.appearance[this.appearance]} in appearance.`;
    }
}
const rate = {
    size: [
        "very small",
        "small",
        "medium-sized",
        "somewhat large",
        "large",
        "giant", 
    ],
    strength: [
        "very weak",
        "weak",
        "strong",
        "somewhat strong",
        "formidable",
        "extremely powerful",
        "invincible",
        "godly", 
    ],
    intelligence: [
        "brainless",
        "unintelligent",
        "somewhat intelligent",
        "intelligent",
        "highly intelligent",
        "most intelligent", 
    ],
    appearance: [
        "disgusting",
        "unsettling",
        "average",
        "beautiful",
        "splendid",
        "indescribable",
        "unimaginable", 
    ]
};
function run() {
    const body = {
        tail: false,
        head: false,
        wings: false,
        hands: false,
        legs: false,
        fingers: false,
        toes: false,
        horns: false,
        animal_ears: false
    };
    Object.keys(body).forEach((x)=>{
        Object.defineProperty(body, x, {
            value: getRandom(Creatures).body_parts[x]
        });
    });
    const similarities = {
        tail: false,
        head: false,
        wings: false,
        hands: false,
        legs: false,
        fingers: false,
        toes: false,
        horns: false,
        animal_ears: false
    };
    Object.keys(similarities).forEach((x)=>{
        similarities[x] = getRandom(Creatures.filter((y)=>y.body_parts[x])).name;
    });
    return {
        body,
        similarities
    };
}
function generateRace(name) {
    const race = new Race();
    if (name) race.name = name;
    return race;
}
export { generateCharacter as generateCharacter };
export { generateName as generateName };
export { generateFantasyName as generateFantasyName };
export { generateRace as generateRace };
const __default6 = [
    "AAA",
    "AARP",
    "ABARTH",
    "ABB",
    "ABBOTT",
    "ABBVIE",
    "ABC",
    "ABLE",
    "ABOGADO",
    "ABUDHABI",
    "AC",
    "ACADEMY",
    "ACCENTURE",
    "ACCOUNTANT",
    "ACCOUNTANTS",
    "ACO",
    "ACTOR",
    "AD",
    "ADAC",
    "ADS",
    "ADULT",
    "AE",
    "AEG",
    "AERO",
    "AETNA",
    "AF",
    "AFL",
    "AFRICA",
    "AG",
    "AGAKHAN",
    "AGENCY",
    "AI",
    "AIG",
    "AIRBUS",
    "AIRFORCE",
    "AIRTEL",
    "AKDN",
    "AL",
    "ALFAROMEO",
    "ALIBABA",
    "ALIPAY",
    "ALLFINANZ",
    "ALLSTATE",
    "ALLY",
    "ALSACE",
    "ALSTOM",
    "AM",
    "AMAZON",
    "AMERICANEXPRESS",
    "AMERICANFAMILY",
    "AMEX",
    "AMFAM",
    "AMICA",
    "AMSTERDAM",
    "ANALYTICS",
    "ANDROID",
    "ANQUAN",
    "ANZ",
    "AO",
    "AOL",
    "APARTMENTS",
    "APP",
    "APPLE",
    "AQ",
    "AQUARELLE",
    "AR",
    "ARAB",
    "ARAMCO",
    "ARCHI",
    "ARMY",
    "ARPA",
    "ART",
    "ARTE",
    "AS",
    "ASDA",
    "ASIA",
    "ASSOCIATES",
    "AT",
    "ATHLETA",
    "ATTORNEY",
    "AU",
    "AUCTION",
    "AUDI",
    "AUDIBLE",
    "AUDIO",
    "AUSPOST",
    "AUTHOR",
    "AUTO",
    "AUTOS",
    "AVIANCA",
    "AW",
    "AWS",
    "AX",
    "AXA",
    "AZ",
    "AZURE",
    "BA",
    "BABY",
    "BAIDU",
    "BANAMEX",
    "BANANAREPUBLIC",
    "BAND",
    "BANK",
    "BAR",
    "BARCELONA",
    "BARCLAYCARD",
    "BARCLAYS",
    "BAREFOOT",
    "BARGAINS",
    "BASEBALL",
    "BASKETBALL",
    "BAUHAUS",
    "BAYERN",
    "BB",
    "BBC",
    "BBT",
    "BBVA",
    "BCG",
    "BCN",
    "BD",
    "BE",
    "BEATS",
    "BEAUTY",
    "BEER",
    "BENTLEY",
    "BERLIN",
    "BEST",
    "BESTBUY",
    "BET",
    "BF",
    "BG",
    "BH",
    "BHARTI",
    "BI",
    "BIBLE",
    "BID",
    "BIKE",
    "BING",
    "BINGO",
    "BIO",
    "BIZ",
    "BJ",
    "BLACK",
    "BLACKFRIDAY",
    "BLOCKBUSTER",
    "BLOG",
    "BLOOMBERG",
    "BLUE",
    "BM",
    "BMS",
    "BMW",
    "BN",
    "BNPPARIBAS",
    "BO",
    "BOATS",
    "BOEHRINGER",
    "BOFA",
    "BOM",
    "BOND",
    "BOO",
    "BOOK",
    "BOOKING",
    "BOSCH",
    "BOSTIK",
    "BOSTON",
    "BOT",
    "BOUTIQUE",
    "BOX",
    "BR",
    "BRADESCO",
    "BRIDGESTONE",
    "BROADWAY",
    "BROKER",
    "BROTHER",
    "BRUSSELS",
    "BS",
    "BT",
    "BUGATTI",
    "BUILD",
    "BUILDERS",
    "BUSINESS",
    "BUY",
    "BUZZ",
    "BV",
    "BW",
    "BY",
    "BZ",
    "BZH",
    "CA",
    "CAB",
    "CAFE",
    "CAL",
    "CALL",
    "CALVINKLEIN",
    "CAM",
    "CAMERA",
    "CAMP",
    "CANCERRESEARCH",
    "CANON",
    "CAPETOWN",
    "CAPITAL",
    "CAPITALONE",
    "CAR",
    "CARAVAN",
    "CARDS",
    "CARE",
    "CAREER",
    "CAREERS",
    "CARS",
    "CASA",
    "CASE",
    "CASH",
    "CASINO",
    "CAT",
    "CATERING",
    "CATHOLIC",
    "CBA",
    "CBN",
    "CBRE",
    "CBS",
    "CC",
    "CD",
    "CENTER",
    "CEO",
    "CERN",
    "CF",
    "CFA",
    "CFD",
    "CG",
    "CH",
    "CHANEL",
    "CHANNEL",
    "CHARITY",
    "CHASE",
    "CHAT",
    "CHEAP",
    "CHINTAI",
    "CHRISTMAS",
    "CHROME",
    "CHURCH",
    "CI",
    "CIPRIANI",
    "CIRCLE",
    "CISCO",
    "CITADEL",
    "CITI",
    "CITIC",
    "CITY",
    "CITYEATS",
    "CK",
    "CL",
    "CLAIMS",
    "CLEANING",
    "CLICK",
    "CLINIC",
    "CLINIQUE",
    "CLOTHING",
    "CLOUD",
    "CLUB",
    "CLUBMED",
    "CM",
    "CN",
    "CO",
    "COACH",
    "CODES",
    "COFFEE",
    "COLLEGE",
    "COLOGNE",
    "COM",
    "COMCAST",
    "COMMBANK",
    "COMMUNITY",
    "COMPANY",
    "COMPARE",
    "COMPUTER",
    "COMSEC",
    "CONDOS",
    "CONSTRUCTION",
    "CONSULTING",
    "CONTACT",
    "CONTRACTORS",
    "COOKING",
    "COOKINGCHANNEL",
    "COOL",
    "COOP",
    "CORSICA",
    "COUNTRY",
    "COUPON",
    "COUPONS",
    "COURSES",
    "CPA",
    "CR",
    "CREDIT",
    "CREDITCARD",
    "CREDITUNION",
    "CRICKET",
    "CROWN",
    "CRS",
    "CRUISE",
    "CRUISES",
    "CU",
    "CUISINELLA",
    "CV",
    "CW",
    "CX",
    "CY",
    "CYMRU",
    "CYOU",
    "CZ",
    "DABUR",
    "DAD",
    "DANCE",
    "DATA",
    "DATE",
    "DATING",
    "DATSUN",
    "DAY",
    "DCLK",
    "DDS",
    "DE",
    "DEAL",
    "DEALER",
    "DEALS",
    "DEGREE",
    "DELIVERY",
    "DELL",
    "DELOITTE",
    "DELTA",
    "DEMOCRAT",
    "DENTAL",
    "DENTIST",
    "DESI",
    "DESIGN",
    "DEV",
    "DHL",
    "DIAMONDS",
    "DIET",
    "DIGITAL",
    "DIRECT",
    "DIRECTORY",
    "DISCOUNT",
    "DISCOVER",
    "DISH",
    "DIY",
    "DJ",
    "DK",
    "DM",
    "DNP",
    "DO",
    "DOCS",
    "DOCTOR",
    "DOG",
    "DOMAINS",
    "DOT",
    "DOWNLOAD",
    "DRIVE",
    "DTV",
    "DUBAI",
    "DUNLOP",
    "DUPONT",
    "DURBAN",
    "DVAG",
    "DVR",
    "DZ",
    "EARTH",
    "EAT",
    "EC",
    "ECO",
    "EDEKA",
    "EDU",
    "EDUCATION",
    "EE",
    "EG",
    "EMAIL",
    "EMERCK",
    "ENERGY",
    "ENGINEER",
    "ENGINEERING",
    "ENTERPRISES",
    "EPSON",
    "EQUIPMENT",
    "ER",
    "ERICSSON",
    "ERNI",
    "ES",
    "ESQ",
    "ESTATE",
    "ET",
    "ETISALAT",
    "EU",
    "EUROVISION",
    "EUS",
    "EVENTS",
    "EXCHANGE",
    "EXPERT",
    "EXPOSED",
    "EXPRESS",
    "EXTRASPACE",
    "FAGE",
    "FAIL",
    "FAIRWINDS",
    "FAITH",
    "FAMILY",
    "FAN",
    "FANS",
    "FARM",
    "FARMERS",
    "FASHION",
    "FAST",
    "FEDEX",
    "FEEDBACK",
    "FERRARI",
    "FERRERO",
    "FI",
    "FIAT",
    "FIDELITY",
    "FIDO",
    "FILM",
    "FINAL",
    "FINANCE",
    "FINANCIAL",
    "FIRE",
    "FIRESTONE",
    "FIRMDALE",
    "FISH",
    "FISHING",
    "FIT",
    "FITNESS",
    "FJ",
    "FK",
    "FLICKR",
    "FLIGHTS",
    "FLIR",
    "FLORIST",
    "FLOWERS",
    "FLY",
    "FM",
    "FO",
    "FOO",
    "FOOD",
    "FOODNETWORK",
    "FOOTBALL",
    "FORD",
    "FOREX",
    "FORSALE",
    "FORUM",
    "FOUNDATION",
    "FOX",
    "FR",
    "FREE",
    "FRESENIUS",
    "FRL",
    "FROGANS",
    "FRONTDOOR",
    "FRONTIER",
    "FTR",
    "FUJITSU",
    "FUN",
    "FUND",
    "FURNITURE",
    "FUTBOL",
    "FYI",
    "GA",
    "GAL",
    "GALLERY",
    "GALLO",
    "GALLUP",
    "GAME",
    "GAMES",
    "GAP",
    "GARDEN",
    "GAY",
    "GB",
    "GBIZ",
    "GD",
    "GDN",
    "GE",
    "GEA",
    "GENT",
    "GENTING",
    "GEORGE",
    "GF",
    "GG",
    "GGEE",
    "GH",
    "GI",
    "GIFT",
    "GIFTS",
    "GIVES",
    "GIVING",
    "GL",
    "GLASS",
    "GLE",
    "GLOBAL",
    "GLOBO",
    "GM",
    "GMAIL",
    "GMBH",
    "GMO",
    "GMX",
    "GN",
    "GODADDY",
    "GOLD",
    "GOLDPOINT",
    "GOLF",
    "GOO",
    "GOODYEAR",
    "GOOG",
    "GOOGLE",
    "GOP",
    "GOT",
    "GOV",
    "GP",
    "GQ",
    "GR",
    "GRAINGER",
    "GRAPHICS",
    "GRATIS",
    "GREEN",
    "GRIPE",
    "GROCERY",
    "GROUP",
    "GS",
    "GT",
    "GU",
    "GUARDIAN",
    "GUCCI",
    "GUGE",
    "GUIDE",
    "GUITARS",
    "GURU",
    "GW",
    "GY",
    "HAIR",
    "HAMBURG",
    "HANGOUT",
    "HAUS",
    "HBO",
    "HDFC",
    "HDFCBANK",
    "HEALTH",
    "HEALTHCARE",
    "HELP",
    "HELSINKI",
    "HERE",
    "HERMES",
    "HGTV",
    "HIPHOP",
    "HISAMITSU",
    "HITACHI",
    "HIV",
    "HK",
    "HKT",
    "HM",
    "HN",
    "HOCKEY",
    "HOLDINGS",
    "HOLIDAY",
    "HOMEDEPOT",
    "HOMEGOODS",
    "HOMES",
    "HOMESENSE",
    "HONDA",
    "HORSE",
    "HOSPITAL",
    "HOST",
    "HOSTING",
    "HOT",
    "HOTELES",
    "HOTELS",
    "HOTMAIL",
    "HOUSE",
    "HOW",
    "HR",
    "HSBC",
    "HT",
    "HU",
    "HUGHES",
    "HYATT",
    "HYUNDAI",
    "IBM",
    "ICBC",
    "ICE",
    "ICU",
    "ID",
    "IE",
    "IEEE",
    "IFM",
    "IKANO",
    "IL",
    "IM",
    "IMAMAT",
    "IMDB",
    "IMMO",
    "IMMOBILIEN",
    "IN",
    "INC",
    "INDUSTRIES",
    "INFINITI",
    "INFO",
    "ING",
    "INK",
    "INSTITUTE",
    "INSURANCE",
    "INSURE",
    "INT",
    "INTERNATIONAL",
    "INTUIT",
    "INVESTMENTS",
    "IO",
    "IPIRANGA",
    "IQ",
    "IR",
    "IRISH",
    "IS",
    "ISMAILI",
    "IST",
    "ISTANBUL",
    "IT",
    "ITAU",
    "ITV",
    "JAGUAR",
    "JAVA",
    "JCB",
    "JE",
    "JEEP",
    "JETZT",
    "JEWELRY",
    "JIO",
    "JLL",
    "JM",
    "JMP",
    "JNJ",
    "JO",
    "JOBS",
    "JOBURG",
    "JOT",
    "JOY",
    "JP",
    "JPMORGAN",
    "JPRS",
    "JUEGOS",
    "JUNIPER",
    "KAUFEN",
    "KDDI",
    "KE",
    "KERRYHOTELS",
    "KERRYLOGISTICS",
    "KERRYPROPERTIES",
    "KFH",
    "KG",
    "KH",
    "KI",
    "KIA",
    "KIDS",
    "KIM",
    "KINDER",
    "KINDLE",
    "KITCHEN",
    "KIWI",
    "KM",
    "KN",
    "KOELN",
    "KOMATSU",
    "KOSHER",
    "KP",
    "KPMG",
    "KPN",
    "KR",
    "KRD",
    "KRED",
    "KUOKGROUP",
    "KW",
    "KY",
    "KYOTO",
    "KZ",
    "LA",
    "LACAIXA",
    "LAMBORGHINI",
    "LAMER",
    "LANCASTER",
    "LANCIA",
    "LAND",
    "LANDROVER",
    "LANXESS",
    "LASALLE",
    "LAT",
    "LATINO",
    "LATROBE",
    "LAW",
    "LAWYER",
    "LB",
    "LC",
    "LDS",
    "LEASE",
    "LECLERC",
    "LEFRAK",
    "LEGAL",
    "LEGO",
    "LEXUS",
    "LGBT",
    "LI",
    "LIDL",
    "LIFE",
    "LIFEINSURANCE",
    "LIFESTYLE",
    "LIGHTING",
    "LIKE",
    "LILLY",
    "LIMITED",
    "LIMO",
    "LINCOLN",
    "LINDE",
    "LINK",
    "LIPSY",
    "LIVE",
    "LIVING",
    "LK",
    "LLC",
    "LLP",
    "LOAN",
    "LOANS",
    "LOCKER",
    "LOCUS",
    "LOFT",
    "LOL",
    "LONDON",
    "LOTTE",
    "LOTTO",
    "LOVE",
    "LPL",
    "LPLFINANCIAL",
    "LR",
    "LS",
    "LT",
    "LTD",
    "LTDA",
    "LU",
    "LUNDBECK",
    "LUXE",
    "LUXURY",
    "LV",
    "LY",
    "MA",
    "MACYS",
    "MADRID",
    "MAIF",
    "MAISON",
    "MAKEUP",
    "MAN",
    "MANAGEMENT",
    "MANGO",
    "MAP",
    "MARKET",
    "MARKETING",
    "MARKETS",
    "MARRIOTT",
    "MARSHALLS",
    "MASERATI",
    "MATTEL",
    "MBA",
    "MC",
    "MCKINSEY",
    "MD",
    "ME",
    "MED",
    "MEDIA",
    "MEET",
    "MELBOURNE",
    "MEME",
    "MEMORIAL",
    "MEN",
    "MENU",
    "MERCKMSD",
    "MG",
    "MH",
    "MIAMI",
    "MICROSOFT",
    "MIL",
    "MINI",
    "MINT",
    "MIT",
    "MITSUBISHI",
    "MK",
    "ML",
    "MLB",
    "MLS",
    "MM",
    "MMA",
    "MN",
    "MO",
    "MOBI",
    "MOBILE",
    "MODA",
    "MOE",
    "MOI",
    "MOM",
    "MONASH",
    "MONEY",
    "MONSTER",
    "MORMON",
    "MORTGAGE",
    "MOSCOW",
    "MOTO",
    "MOTORCYCLES",
    "MOV",
    "MOVIE",
    "MP",
    "MQ",
    "MR",
    "MS",
    "MSD",
    "MT",
    "MTN",
    "MTR",
    "MU",
    "MUSEUM",
    "MUSIC",
    "MUTUAL",
    "MV",
    "MW",
    "MX",
    "MY",
    "MZ",
    "NA",
    "NAB",
    "NAGOYA",
    "NAME",
    "NATURA",
    "NAVY",
    "NBA",
    "NC",
    "NE",
    "NEC",
    "NET",
    "NETBANK",
    "NETFLIX",
    "NETWORK",
    "NEUSTAR",
    "NEW",
    "NEWS",
    "NEXT",
    "NEXTDIRECT",
    "NEXUS",
    "NF",
    "NFL",
    "NG",
    "NGO",
    "NHK",
    "NI",
    "NICO",
    "NIKE",
    "NIKON",
    "NINJA",
    "NISSAN",
    "NISSAY",
    "NL",
    "NO",
    "NOKIA",
    "NORTHWESTERNMUTUAL",
    "NORTON",
    "NOW",
    "NOWRUZ",
    "NOWTV",
    "NP",
    "NR",
    "NRA",
    "NRW",
    "NTT",
    "NU",
    "NYC",
    "NZ",
    "OBI",
    "OBSERVER",
    "OFFICE",
    "OKINAWA",
    "OLAYAN",
    "OLAYANGROUP",
    "OLDNAVY",
    "OLLO",
    "OM",
    "OMEGA",
    "ONE",
    "ONG",
    "ONL",
    "ONLINE",
    "OOO",
    "OPEN",
    "ORACLE",
    "ORANGE",
    "ORG",
    "ORGANIC",
    "ORIGINS",
    "OSAKA",
    "OTSUKA",
    "OTT",
    "OVH",
    "PA",
    "PAGE",
    "PANASONIC",
    "PARIS",
    "PARS",
    "PARTNERS",
    "PARTS",
    "PARTY",
    "PASSAGENS",
    "PAY",
    "PCCW",
    "PE",
    "PET",
    "PF",
    "PFIZER",
    "PG",
    "PH",
    "PHARMACY",
    "PHD",
    "PHILIPS",
    "PHONE",
    "PHOTO",
    "PHOTOGRAPHY",
    "PHOTOS",
    "PHYSIO",
    "PICS",
    "PICTET",
    "PICTURES",
    "PID",
    "PIN",
    "PING",
    "PINK",
    "PIONEER",
    "PIZZA",
    "PK",
    "PL",
    "PLACE",
    "PLAY",
    "PLAYSTATION",
    "PLUMBING",
    "PLUS",
    "PM",
    "PN",
    "PNC",
    "POHL",
    "POKER",
    "POLITIE",
    "PORN",
    "POST",
    "PR",
    "PRAMERICA",
    "PRAXI",
    "PRESS",
    "PRIME",
    "PRO",
    "PROD",
    "PRODUCTIONS",
    "PROF",
    "PROGRESSIVE",
    "PROMO",
    "PROPERTIES",
    "PROPERTY",
    "PROTECTION",
    "PRU",
    "PRUDENTIAL",
    "PS",
    "PT",
    "PUB",
    "PW",
    "PWC",
    "PY",
    "QA",
    "QPON",
    "QUEBEC",
    "QUEST",
    "RACING",
    "RADIO",
    "RE",
    "READ",
    "REALESTATE",
    "REALTOR",
    "REALTY",
    "RECIPES",
    "RED",
    "REDSTONE",
    "REDUMBRELLA",
    "REHAB",
    "REISE",
    "REISEN",
    "REIT",
    "RELIANCE",
    "REN",
    "RENT",
    "RENTALS",
    "REPAIR",
    "REPORT",
    "REPUBLICAN",
    "REST",
    "RESTAURANT",
    "REVIEW",
    "REVIEWS",
    "REXROTH",
    "RICH",
    "RICHARDLI",
    "RICOH",
    "RIL",
    "RIO",
    "RIP",
    "RO",
    "ROCHER",
    "ROCKS",
    "RODEO",
    "ROGERS",
    "ROOM",
    "RS",
    "RSVP",
    "RU",
    "RUGBY",
    "RUHR",
    "RUN",
    "RW",
    "RWE",
    "RYUKYU",
    "SA",
    "SAARLAND",
    "SAFE",
    "SAFETY",
    "SAKURA",
    "SALE",
    "SALON",
    "SAMSCLUB",
    "SAMSUNG",
    "SANDVIK",
    "SANDVIKCOROMANT",
    "SANOFI",
    "SAP",
    "SARL",
    "SAS",
    "SAVE",
    "SAXO",
    "SB",
    "SBI",
    "SBS",
    "SC",
    "SCA",
    "SCB",
    "SCHAEFFLER",
    "SCHMIDT",
    "SCHOLARSHIPS",
    "SCHOOL",
    "SCHULE",
    "SCHWARZ",
    "SCIENCE",
    "SCOT",
    "SD",
    "SE",
    "SEARCH",
    "SEAT",
    "SECURE",
    "SECURITY",
    "SEEK",
    "SELECT",
    "SENER",
    "SERVICES",
    "SES",
    "SEVEN",
    "SEW",
    "SEX",
    "SEXY",
    "SFR",
    "SG",
    "SH",
    "SHANGRILA",
    "SHARP",
    "SHAW",
    "SHELL",
    "SHIA",
    "SHIKSHA",
    "SHOES",
    "SHOP",
    "SHOPPING",
    "SHOUJI",
    "SHOW",
    "SHOWTIME",
    "SI",
    "SILK",
    "SINA",
    "SINGLES",
    "SITE",
    "SJ",
    "SK",
    "SKI",
    "SKIN",
    "SKY",
    "SKYPE",
    "SL",
    "SLING",
    "SM",
    "SMART",
    "SMILE",
    "SN",
    "SNCF",
    "SO",
    "SOCCER",
    "SOCIAL",
    "SOFTBANK",
    "SOFTWARE",
    "SOHU",
    "SOLAR",
    "SOLUTIONS",
    "SONG",
    "SONY",
    "SOY",
    "SPA",
    "SPACE",
    "SPORT",
    "SPOT",
    "SR",
    "SRL",
    "SS",
    "ST",
    "STADA",
    "STAPLES",
    "STAR",
    "STATEBANK",
    "STATEFARM",
    "STC",
    "STCGROUP",
    "STOCKHOLM",
    "STORAGE",
    "STORE",
    "STREAM",
    "STUDIO",
    "STUDY",
    "STYLE",
    "SU",
    "SUCKS",
    "SUPPLIES",
    "SUPPLY",
    "SUPPORT",
    "SURF",
    "SURGERY",
    "SUZUKI",
    "SV",
    "SWATCH",
    "SWISS",
    "SX",
    "SY",
    "SYDNEY",
    "SYSTEMS",
    "SZ",
    "TAB",
    "TAIPEI",
    "TALK",
    "TAOBAO",
    "TARGET",
    "TATAMOTORS",
    "TATAR",
    "TATTOO",
    "TAX",
    "TAXI",
    "TC",
    "TCI",
    "TD",
    "TDK",
    "TEAM",
    "TECH",
    "TECHNOLOGY",
    "TEL",
    "TEMASEK",
    "TENNIS",
    "TEVA",
    "TF",
    "TG",
    "TH",
    "THD",
    "THEATER",
    "THEATRE",
    "TIAA",
    "TICKETS",
    "TIENDA",
    "TIFFANY",
    "TIPS",
    "TIRES",
    "TIROL",
    "TJ",
    "TJMAXX",
    "TJX",
    "TK",
    "TKMAXX",
    "TL",
    "TM",
    "TMALL",
    "TN",
    "TO",
    "TODAY",
    "TOKYO",
    "TOOLS",
    "TOP",
    "TORAY",
    "TOSHIBA",
    "TOTAL",
    "TOURS",
    "TOWN",
    "TOYOTA",
    "TOYS",
    "TR",
    "TRADE",
    "TRADING",
    "TRAINING",
    "TRAVEL",
    "TRAVELCHANNEL",
    "TRAVELERS",
    "TRAVELERSINSURANCE",
    "TRUST",
    "TRV",
    "TT",
    "TUBE",
    "TUI",
    "TUNES",
    "TUSHU",
    "TV",
    "TVS",
    "TW",
    "TZ",
    "UA",
    "UBANK",
    "UBS",
    "UG",
    "UK",
    "UNICOM",
    "UNIVERSITY",
    "UNO",
    "UOL",
    "UPS",
    "US",
    "UY",
    "UZ",
    "VA",
    "VACATIONS",
    "VANA",
    "VANGUARD",
    "VC",
    "VE",
    "VEGAS",
    "VENTURES",
    "VERISIGN",
    "VERSICHERUNG",
    "VET",
    "VG",
    "VI",
    "VIAJES",
    "VIDEO",
    "VIG",
    "VIKING",
    "VILLAS",
    "VIN",
    "VIP",
    "VIRGIN",
    "VISA",
    "VISION",
    "VIVA",
    "VIVO",
    "VLAANDEREN",
    "VN",
    "VODKA",
    "VOLKSWAGEN",
    "VOLVO",
    "VOTE",
    "VOTING",
    "VOTO",
    "VOYAGE",
    "VU",
    "VUELOS",
    "WALES",
    "WALMART",
    "WALTER",
    "WANG",
    "WANGGOU",
    "WATCH",
    "WATCHES",
    "WEATHER",
    "WEATHERCHANNEL",
    "WEBCAM",
    "WEBER",
    "WEBSITE",
    "WED",
    "WEDDING",
    "WEIBO",
    "WEIR",
    "WF",
    "WHOSWHO",
    "WIEN",
    "WIKI",
    "WILLIAMHILL",
    "WIN",
    "WINDOWS",
    "WINE",
    "WINNERS",
    "WME",
    "WOLTERSKLUWER",
    "WOODSIDE",
    "WORK",
    "WORKS",
    "WORLD",
    "WOW",
    "WS",
    "WTC",
    "WTF",
    "XBOX",
    "XEROX",
    "XFINITY",
    "XIHUAN",
    "XIN",
    "XN--11B4C3D",
    "XN--1CK2E1B",
    "XN--1QQW23A",
    "XN--2SCRJ9C",
    "XN--30RR7Y",
    "XN--3BST00M",
    "XN--3DS443G",
    "XN--3E0B707E",
    "XN--3HCRJ9C",
    "XN--3PXU8K",
    "XN--42C2D9A",
    "XN--45BR5CYL",
    "XN--45BRJ9C",
    "XN--45Q11C",
    "XN--4DBRK0CE",
    "XN--4GBRIM",
    "XN--54B7FTA0CC",
    "XN--55QW42G",
    "XN--55QX5D",
    "XN--5SU34J936BGSG",
    "XN--5TZM5G",
    "XN--6FRZ82G",
    "XN--6QQ986B3XL",
    "XN--80ADXHKS",
    "XN--80AO21A",
    "XN--80AQECDR1A",
    "XN--80ASEHDB",
    "XN--80ASWG",
    "XN--8Y0A063A",
    "XN--90A3AC",
    "XN--90AE",
    "XN--90AIS",
    "XN--9DBQ2A",
    "XN--9ET52U",
    "XN--9KRT00A",
    "XN--B4W605FERD",
    "XN--BCK1B9A5DRE4C",
    "XN--C1AVG",
    "XN--C2BR7G",
    "XN--CCK2B3B",
    "XN--CCKWCXETD",
    "XN--CG4BKI",
    "XN--CLCHC0EA0B2G2A9GCD",
    "XN--CZR694B",
    "XN--CZRS0T",
    "XN--CZRU2D",
    "XN--D1ACJ3B",
    "XN--D1ALF",
    "XN--E1A4C",
    "XN--ECKVDTC9D",
    "XN--EFVY88H",
    "XN--FCT429K",
    "XN--FHBEI",
    "XN--FIQ228C5HS",
    "XN--FIQ64B",
    "XN--FIQS8S",
    "XN--FIQZ9S",
    "XN--FJQ720A",
    "XN--FLW351E",
    "XN--FPCRJ9C3D",
    "XN--FZC2C9E2C",
    "XN--FZYS8D69UVGM",
    "XN--G2XX48C",
    "XN--GCKR3F0F",
    "XN--GECRJ9C",
    "XN--GK3AT1E",
    "XN--H2BREG3EVE",
    "XN--H2BRJ9C",
    "XN--H2BRJ9C8C",
    "XN--HXT814E",
    "XN--I1B6B1A6A2E",
    "XN--IMR513N",
    "XN--IO0A7I",
    "XN--J1AEF",
    "XN--J1AMH",
    "XN--J6W193G",
    "XN--JLQ480N2RG",
    "XN--JLQ61U9W7B",
    "XN--JVR189M",
    "XN--KCRX77D1X4A",
    "XN--KPRW13D",
    "XN--KPRY57D",
    "XN--KPUT3I",
    "XN--L1ACC",
    "XN--LGBBAT1AD8J",
    "XN--MGB9AWBF",
    "XN--MGBA3A3EJT",
    "XN--MGBA3A4F16A",
    "XN--MGBA7C0BBN0A",
    "XN--MGBAAKC7DVF",
    "XN--MGBAAM7A8H",
    "XN--MGBAB2BD",
    "XN--MGBAH1A3HJKRD",
    "XN--MGBAI9AZGQP6J",
    "XN--MGBAYH7GPA",
    "XN--MGBBH1A",
    "XN--MGBBH1A71E",
    "XN--MGBC0A9AZCG",
    "XN--MGBCA7DZDO",
    "XN--MGBCPQ6GPA1A",
    "XN--MGBERP4A5D4AR",
    "XN--MGBGU82A",
    "XN--MGBI4ECEXP",
    "XN--MGBPL2FH",
    "XN--MGBT3DHD",
    "XN--MGBTX2B",
    "XN--MGBX4CD0AB",
    "XN--MIX891F",
    "XN--MK1BU44C",
    "XN--MXTQ1M",
    "XN--NGBC5AZD",
    "XN--NGBE9E0A",
    "XN--NGBRX",
    "XN--NODE",
    "XN--NQV7F",
    "XN--NQV7FS00EMA",
    "XN--NYQY26A",
    "XN--O3CW4H",
    "XN--OGBPF8FL",
    "XN--OTU796D",
    "XN--P1ACF",
    "XN--P1AI",
    "XN--PGBS0DH",
    "XN--PSSY2U",
    "XN--Q7CE6A",
    "XN--Q9JYB4C",
    "XN--QCKA1PMC",
    "XN--QXA6A",
    "XN--QXAM",
    "XN--RHQV96G",
    "XN--ROVU88B",
    "XN--RVC1E0AM3E",
    "XN--S9BRJ9C",
    "XN--SES554G",
    "XN--T60B56A",
    "XN--TCKWE",
    "XN--TIQ49XQYJ",
    "XN--UNUP4Y",
    "XN--VERMGENSBERATER-CTB",
    "XN--VERMGENSBERATUNG-PWB",
    "XN--VHQUV",
    "XN--VUQ861B",
    "XN--W4R85EL8FHU5DNRA",
    "XN--W4RS40L",
    "XN--WGBH1C",
    "XN--WGBL6A",
    "XN--XHQ521B",
    "XN--XKC2AL3HYE2A",
    "XN--XKC2DL3A5EE0H",
    "XN--Y9A3AQ",
    "XN--YFRO4I67O",
    "XN--YGBI2AMMX",
    "XN--ZFR164B",
    "XXX",
    "XYZ",
    "YACHTS",
    "YAHOO",
    "YAMAXUN",
    "YANDEX",
    "YE",
    "YODOBASHI",
    "YOGA",
    "YOKOHAMA",
    "YOU",
    "YOUTUBE",
    "YT",
    "YUN",
    "ZA",
    "ZAPPOS",
    "ZARA",
    "ZERO",
    "ZIP",
    "ZM",
    "ZONE",
    "ZUERICH",
    "ZW", 
];
const __default7 = [
    "co",
    "org",
    "edu",
    "ac",
    "gov"
];
const __default8 = [
    "gmail.com",
    "yahoo.com",
    "mail.com",
    "email.com",
    "hotmail.com",
    "aol.com", 
];
const __default9 = [
    "de",
    "di",
    "der",
    "no",
    "of",
    "von"
];
function generateEmail(common = false) {
    return `${generateName(3 + Math.floor(Math.random() * 5)).toLowerCase()}${Math.random() < 0.5 ? "." : Math.random() < 0.5 ? getRandom(__default9) : ""}${generateName(3 + Math.floor(Math.random() * 5)).toLowerCase()}@${common ? getRandom(__default8) : `${generateName(4 + Math.floor(Math.random() * 3)).toLowerCase()}.${Math.random() < 0.5 ? getRandom(__default7) : ""}${getRandom(__default6)}`}`;
}
export { generateEmail as generateEmail };
const Creatures1 = [
    {
        name: "cat",
        plural: "cats",
        level: 1,
        affiliation: 0,
        intelligence: 1,
        size: 1,
        body_parts: {
            tail: true,
            head: true,
            wings: false,
            hands: true,
            legs: true,
            fingers: true,
            toes: true,
            horns: false,
            animal_ears: true
        },
        magical: false,
        appearance: 3
    },
    {
        name: "kitten",
        plural: "kittens",
        level: 1,
        affiliation: 0,
        intelligence: 1,
        size: 1,
        body_parts: {
            tail: true,
            head: true,
            wings: false,
            hands: true,
            legs: true,
            fingers: true,
            toes: true,
            horns: false,
            animal_ears: true
        },
        magical: false,
        appearance: 3
    },
    {
        name: "watermelon",
        plural: "watermelons",
        level: 1,
        affiliation: 0,
        intelligence: 1,
        size: 1,
        body_parts: {
            tail: false,
            head: false,
            wings: false,
            hands: false,
            legs: false,
            fingers: false,
            toes: false,
            horns: false,
            animal_ears: false
        },
        magical: false,
        appearance: 3
    },
    {
        name: "project manager",
        plural: "project managers",
        level: 1,
        affiliation: 0,
        intelligence: 1,
        size: 1,
        body_parts: {
            tail: false,
            head: true,
            wings: false,
            hands: true,
            legs: true,
            fingers: true,
            toes: true,
            horns: true,
            animal_ears: false
        },
        magical: false,
        appearance: 3
    },
    {
        name: "nokia",
        plural: "nokia",
        level: 1,
        affiliation: 0,
        intelligence: 1,
        size: 1,
        body_parts: {
            tail: false,
            head: false,
            wings: false,
            hands: false,
            legs: false,
            fingers: false,
            toes: false,
            horns: false,
            animal_ears: false
        },
        magical: false,
        appearance: 3
    },
    {
        name: "cock",
        plural: "cocks",
        level: 1,
        affiliation: 0,
        intelligence: 1,
        size: 1,
        body_parts: {
            tail: true,
            head: true,
            wings: true,
            hands: false,
            legs: true,
            fingers: false,
            toes: true,
            horns: false,
            animal_ears: true
        },
        magical: false,
        appearance: 3
    },
    {
        name: "chicken",
        plural: "chickens",
        level: 1,
        affiliation: 0,
        intelligence: 1,
        size: 1,
        body_parts: {
            tail: true,
            head: true,
            wings: true,
            hands: false,
            legs: true,
            fingers: false,
            toes: true,
            horns: false,
            animal_ears: false
        },
        magical: false,
        appearance: 3
    },
    {
        name: "sheep",
        plural: "sheeps",
        level: 1,
        affiliation: 0,
        intelligence: 1,
        size: 1,
        body_parts: {
            tail: true,
            head: true,
            wings: false,
            hands: true,
            legs: true,
            fingers: true,
            toes: true,
            horns: false,
            animal_ears: true
        },
        magical: false,
        appearance: 3
    },
    {
        name: "mule",
        plural: "mules",
        level: 1,
        affiliation: 0,
        intelligence: 1,
        size: 1,
        body_parts: {
            tail: true,
            head: true,
            wings: false,
            hands: true,
            legs: true,
            fingers: true,
            toes: true,
            horns: false,
            animal_ears: true
        },
        magical: false,
        appearance: 3
    },
    {
        name: "horse",
        plural: "horses",
        level: 1,
        affiliation: 0,
        intelligence: 1,
        size: 1,
        body_parts: {
            tail: true,
            head: true,
            wings: false,
            hands: true,
            legs: true,
            fingers: true,
            toes: true,
            horns: false,
            animal_ears: true
        },
        magical: false,
        appearance: 3
    },
    {
        name: "grizzly",
        plural: "grizzlies",
        level: 1,
        affiliation: 0,
        intelligence: 1,
        size: 1,
        body_parts: {
            tail: true,
            head: true,
            wings: false,
            hands: true,
            legs: true,
            fingers: true,
            toes: true,
            horns: false,
            animal_ears: true
        },
        magical: false,
        appearance: 3
    },
    {
        name: "leopard",
        plural: "leopards",
        level: 1,
        affiliation: 0,
        intelligence: 1,
        size: 1,
        body_parts: {
            tail: true,
            head: true,
            wings: false,
            hands: true,
            legs: true,
            fingers: true,
            toes: true,
            horns: false,
            animal_ears: true
        },
        magical: false,
        appearance: 3
    },
    {
        name: "spider",
        plural: "spiders",
        level: 1,
        affiliation: 0,
        intelligence: 1,
        size: 1,
        body_parts: {
            tail: false,
            head: true,
            wings: false,
            hands: false,
            legs: true,
            fingers: false,
            toes: false,
            horns: false,
            animal_ears: false
        },
        magical: false,
        appearance: 3
    },
    {
        name: "fly",
        plural: "flies",
        level: 1,
        affiliation: 0,
        intelligence: 1,
        size: 1,
        body_parts: {
            tail: false,
            head: true,
            wings: true,
            hands: false,
            legs: true,
            fingers: false,
            toes: false,
            horns: false,
            animal_ears: false
        },
        magical: false,
        appearance: 3
    },
    {
        name: "crocodile",
        plural: "crocodiles",
        level: 1,
        affiliation: 0,
        intelligence: 1,
        size: 1,
        body_parts: {
            tail: true,
            head: true,
            wings: false,
            hands: true,
            legs: true,
            fingers: true,
            toes: true,
            horns: false,
            animal_ears: false
        },
        magical: false,
        appearance: 3
    },
    {
        name: "gorilla",
        plural: "gorillas",
        level: 1,
        affiliation: 0,
        intelligence: 1,
        size: 1,
        body_parts: {
            tail: true,
            head: true,
            wings: false,
            hands: true,
            legs: true,
            fingers: true,
            toes: true,
            horns: false,
            animal_ears: false
        },
        magical: false,
        appearance: 3
    },
    {
        name: "fox",
        plural: "foxes",
        level: 1,
        affiliation: 0,
        intelligence: 1,
        size: 1,
        body_parts: {
            tail: true,
            head: true,
            wings: false,
            hands: true,
            legs: true,
            fingers: true,
            toes: true,
            horns: false,
            animal_ears: true
        },
        magical: false,
        appearance: 3
    },
    {
        name: "puppy",
        plural: "puppies",
        level: 1,
        affiliation: 0,
        intelligence: 1,
        size: 1,
        body_parts: {
            tail: true,
            head: true,
            wings: false,
            hands: true,
            legs: true,
            fingers: true,
            toes: true,
            horns: false,
            animal_ears: true
        },
        magical: false,
        appearance: 3
    },
    {
        name: "dog",
        plural: "dogs",
        level: 1,
        affiliation: 0,
        intelligence: 1,
        size: 1,
        body_parts: {
            tail: true,
            head: true,
            wings: false,
            hands: true,
            legs: true,
            fingers: true,
            toes: true,
            horns: false,
            animal_ears: true
        },
        magical: false,
        appearance: 3
    },
    {
        name: "chimpanzee",
        plural: "chimpanzees",
        level: 1,
        affiliation: 0,
        intelligence: 3,
        size: 1,
        body_parts: {
            tail: true,
            head: true,
            wings: false,
            hands: true,
            legs: true,
            fingers: true,
            toes: true,
            horns: false,
            animal_ears: false
        },
        magical: false,
        appearance: 3
    },
    {
        name: "polar bear",
        plural: "polar bears",
        level: 1,
        affiliation: 0,
        intelligence: 1,
        size: 1,
        body_parts: {
            tail: true,
            head: true,
            wings: false,
            hands: true,
            legs: true,
            fingers: true,
            toes: true,
            horns: false,
            animal_ears: true
        },
        magical: false,
        appearance: 3
    },
    {
        name: "wolf",
        plural: "wolves",
        level: 1,
        affiliation: 0,
        intelligence: 1,
        size: 1,
        body_parts: {
            tail: true,
            head: true,
            wings: false,
            hands: true,
            legs: true,
            fingers: true,
            toes: true,
            horns: false,
            animal_ears: true
        },
        magical: false,
        appearance: 3
    },
    {
        name: "snake",
        plural: "snakes",
        level: 1,
        affiliation: 0,
        intelligence: 1,
        size: 1,
        body_parts: {
            tail: true,
            head: true,
            wings: false,
            hands: false,
            legs: false,
            fingers: false,
            toes: false,
            horns: false,
            animal_ears: false
        },
        magical: false,
        appearance: 3
    },
    {
        name: "ant",
        plural: "ants",
        level: 1,
        affiliation: 0,
        intelligence: 1,
        size: 1,
        body_parts: {
            tail: true,
            head: true,
            wings: false,
            hands: true,
            legs: true,
            fingers: true,
            toes: true,
            horns: false,
            animal_ears: false
        },
        magical: false,
        appearance: 3
    },
    {
        name: "serial killer",
        plural: "serial killers",
        level: 1,
        affiliation: 0,
        intelligence: 1,
        size: 1,
        body_parts: {
            tail: false,
            head: true,
            wings: false,
            hands: true,
            legs: true,
            fingers: true,
            toes: true,
            horns: false,
            animal_ears: false
        },
        magical: false,
        appearance: 3
    },
    {
        name: "catfood",
        plural: "catfood",
        level: 1,
        affiliation: 0,
        intelligence: 1,
        size: 1,
        body_parts: {
            tail: false,
            head: false,
            wings: false,
            hands: false,
            legs: false,
            fingers: false,
            toes: false,
            horns: false,
            animal_ears: false
        },
        magical: false,
        appearance: 3
    },
    {
        name: "pumpkin",
        plural: "pumpkins",
        level: 1,
        affiliation: 0,
        intelligence: 1,
        size: 1,
        body_parts: {
            tail: false,
            head: true,
            wings: false,
            hands: false,
            legs: false,
            fingers: false,
            toes: false,
            horns: false,
            animal_ears: false
        },
        magical: false,
        appearance: 3
    },
    {
        name: "spider",
        plural: "spiders",
        level: 1,
        affiliation: 0,
        intelligence: 1,
        size: 1,
        body_parts: {
            tail: false,
            head: true,
            wings: false,
            hands: false,
            legs: true,
            fingers: false,
            toes: false,
            horns: false,
            animal_ears: false
        },
        magical: false,
        appearance: 3
    },
    {
        name: "centipede",
        plural: "centipedes",
        level: 1,
        affiliation: 0,
        intelligence: 1,
        size: 1,
        body_parts: {
            tail: true,
            head: true,
            wings: false,
            hands: false,
            legs: true,
            fingers: false,
            toes: false,
            horns: false,
            animal_ears: false
        },
        magical: false,
        appearance: 3
    },
    {
        name: "clown",
        plural: "clowns",
        level: 1,
        affiliation: 0,
        intelligence: 1,
        size: 1,
        body_parts: {
            tail: false,
            head: true,
            wings: false,
            hands: true,
            legs: true,
            fingers: true,
            toes: true,
            horns: false,
            animal_ears: false
        },
        magical: false,
        appearance: 3
    },
    {
        name: "godzilla",
        plural: "godzillas",
        level: 1,
        affiliation: 0,
        intelligence: 1,
        size: 1,
        body_parts: {
            tail: true,
            head: true,
            wings: false,
            hands: true,
            legs: true,
            fingers: true,
            toes: true,
            horns: false,
            animal_ears: true
        },
        magical: false,
        appearance: 3
    },
    {
        name: "villager",
        plural: "villagers",
        level: 1,
        affiliation: 0,
        intelligence: 1,
        size: 1,
        body_parts: {
            tail: false,
            head: true,
            wings: false,
            hands: true,
            legs: true,
            fingers: true,
            toes: true,
            horns: false,
            animal_ears: false
        },
        magical: false,
        appearance: 3
    },
    {
        name: "yakuza",
        plural: "yakuza",
        level: 1,
        affiliation: 0,
        intelligence: 1,
        size: 1,
        body_parts: {
            tail: false,
            head: true,
            wings: false,
            hands: true,
            legs: true,
            fingers: true,
            toes: true,
            horns: false,
            animal_ears: false
        },
        magical: false,
        appearance: 3
    },
    {
        name: "lion",
        plural: "lions",
        level: 1,
        affiliation: 0,
        intelligence: 1,
        size: 1,
        body_parts: {
            tail: true,
            head: true,
            wings: false,
            hands: true,
            legs: true,
            fingers: true,
            toes: true,
            horns: false,
            animal_ears: true
        },
        magical: false,
        appearance: 3
    }, 
];
const __default10 = [
    "north",
    "east",
    "west",
    "south"
];
const __default11 = [
    "friendship",
    "training",
    "cheats",
    "darkness",
    "light",
    "flames",
    "wind",
    "laziness",
    "dancing",
    "math",
    "eighth grade syndrome",
    "edginess",
    "cringe",
    "technology",
    "science",
    "religion",
    "outsmarting",
    "workout", 
];
const creatures = Creatures.concat(Creatures1);
const { actions , fight , join  } = __default1;
const penance = (name)=>{
    const ml = generateCharacter();
    const fl = generateCharacter();
    const goodcreature = getRandom(creatures.filter((x)=>x.affiliation === 1 || x.affiliation === 0));
    const evilcreature = getRandom(creatures.filter((x)=>x.affiliation === -1 || x.affiliation === 0));
    const evilcreature2 = getRandom(creatures.filter((x)=>(x.affiliation === -1 || x.affiliation === 0) && x !== evilcreature));
    const rand = Math.random();
    return `${name ? name : `The ${ml}`} ${rand > 0.5 ? `and the ${fl} ${getRandom(join)} to ` : ``}${Math.random() < 0.5 ? rand > 0.5 ? getRandom(actions.singular) : getRandom(actions.plural) : `${getRandom(fight)}${rand > 0.5 ? `` : `s`}`} the${Math.random() < 0.5 ? ` ${evil()}` : ``} ${Math.random() < 0.5 ? generateCharacter() : evilcreature.name}${Math.random() < 0.5 ? `, ${capitalize(generateFantasyName())},` : ``}${Math.random() < 0.5 ? ` with the help of the ${goodcreature.plural}${Math.random() < 0.5 ? ` of ${Math.random() < 0.5 ? `the ${getRandom(__default10)}` : capitalize(generateName(4 + Math.floor(Math.random() * 3)))}` : ``}` : Math.random() < 0.5 ? ` facing powerful enemies from the ${evilcreature2.name} clan` : Math.random() < 0.5 ? ` using the power of ${getRandom(__default11)}` : ``}${Math.random() < 0.5 ? rand > 0.5 ? ` and save the world` : ` and saves the world` : Math.random() < 0.5 ? ` for the sake of their peaceful life` : Math.random() < 0.5 ? ` to reach the final treasure` : Math.random() < 0.5 ? ` to protect what is important to them` : Math.random() < 0.5 ? ` to protect the smiles of innocent children` : Math.random() < 0.5 ? ` to commit war crimes` : Math.random() < 0.5 ? ` to avenge the ${generateCharacter()}` : Math.random() < 0.5 ? ` for world peace` : Math.random() < 0.5 ? ` but end up forming a truce instead` : Math.random() < 0.5 ? ` but end up with a crushing defeat` : ` but tragically die`}.`;
};
function evil() {
    const evilstuff = [
        "demonic",
        "vile",
        "evil",
        "merciless",
        "greedy",
        "ambitious",
        "giant",
        "mecha",
        "divine",
        "almighty",
        "godly",
        "corrupt",
        "angelic", 
    ];
    return getRandom(evilstuff);
}
const __default12 = [
    "friends",
    "family",
    "best friend",
    "parents",
    "mother",
    "father",
    "grandparents",
    "classmates",
    "grandpa",
    "grandma",
    "lonely ass",
    "tamagotchi",
    "pokemon",
    "favorite streamer",
    "college professor",
    "imaginary friend",
    "air friend",
    "sleep paralysis demon",
    "in-game character",
    "most important person",
    "school principal",
    "teacher from kindergarten",
    "pet spider",
    "loved ones",
    "favorite character",
    "disgusting self",
    "senior",
    "junior",
    "great-grandchild",
    "great-grandchildren",
    "phone",
    "internet friends",
    "pet ant",
    "donkey",
    "cat",
    "rock"
];
const __default13 = [
    "kidnapped",
    "hacked",
    "stabbed",
    "pushed from a cliff",
    "mutilated",
    "eaten alive",
    "possessed by an evil spirit",
    "spirited away",
    "hit by a car",
    "hit by a truck",
    "hit by a train",
    "thrown away from a flying airplane",
    "abducted by aliens",
    "burned alive",
    "caught in an explosion",
    "mauled by a bear",
    "mugged",
    "bitten by a snake",
    "poisoned",
    "crushed by an elevator",
    "caught in a stampede",
    "starved to death",
    "hit by lightning",
    "stabbed by a killer",
    "eaten by a shark",
    "caught in a tsunami",
    "stuck in an elevator",
    "shot by a stray bullet",
    "buried alive",
    "caught off-guard by the sleep paralysis demon",
    "eaten by monsters",
    "tossed from a cliff",
    "tied up and tossed into the Atlantic ocean",
    "tied up and tossed into the Pacific ocean",
    "tied up and tossed into the Indian ocean",
    "taken to Brazil",
    "thrown into gulag",
    "bonked by cheems",
    "killed by the imposter",
    "impaled by an umbrella",
    "turned into fumo",
    "returned to monke",
    "killed by herobrine",
    "eaten by ants",
    "electrocuted by a pikachu",
    "forced to eat pizza with choco chips and wasabi sauce",
    "discovered by a discord mod",
    "turned into a discord mod",
    "eaten by a llama",
    "thrown into a snake pit",
    "decapitated by a piece of paper",
    "ejected into the space",
    "forced to watch Dragon Ball Evolution",
    "burned at the stakes",
    "discovered by a plague doctor",
    "down with a fatal disease after eating moldy bread",
    "down with pneumonia",
    "crushed by an elephant",
    "assaulted by a yandere",
    "assaulted by a stalker",
    "mutilated alive",
    "killed by sunlight after being a shut-in for years", 
];
const { death , forward , intro , message  } = __default1;
const generateChainMail = (name)=>{
    return `${getRandom(intro)} ${name ? name : capitalize(generateName(4 + Math.floor(Math.random() * 5)).toLowerCase())}. ${Math.random() > 0.5 ? `${Math.floor(Math.random() * 52)} years ago,` : `When I was ${5 + Math.floor(Math.random() * 12)}${Math.random() > 0.5 ? ` years old` : ""},`} I was ${getRandom(__default13)} and ${getRandom(death)}. ${capitalize(getRandom(forward))} this ${getRandom(message)} to ${5 + Math.floor(Math.random() * 5) * 10} people or ${Math.random() > 0.5 ? `you` : `your ${getRandom(__default12)}`} will be ${getRandom(__default13)}.`;
};
export { generateChainMail as generateChainMail };
function generateStory(mc) {
    return penance(mc || "");
}
export { generateStory as generateStory };
function generateString(lenn) {
    if (!lenn) lenn = 4 + Math.floor(Math.random() * 5);
    let phrase = Math.random() > 0.5 ? `${Math.floor(Math.random() * 10)}` : Math.random() > 0.5 ? getRandom(alphabet) : getRandom(alphabet).toLowerCase();
    for(let pointer = 0; pointer < lenn - 1; ++pointer){
        const chances = Math.random();
        if (chances < 0.3) phrase += getRandom(alphabet);
        else if (chances > 0.3 && chances < 0.7) {
            phrase += getRandom(alphabet).toLowerCase();
        } else phrase += Math.floor(Math.random() * 10);
    }
    return phrase;
}
export { generateString as generateString };
const __default14 = (txt)=>{
    if (!txt) return "";
    return txt.replace(/(?:r|l)/g, "w").replace(/(?:R|L)/g, "W").replace(/n([aeou])/g, "ny$1").replace(/N([aeou])/g, "Ny$1").replace(/N([AEOU])/g, "Ny$1").replace(/nyny/g, "nny").replace(/NyNy/g, "NNy");
};
const __default15 = (txt)=>{
    if (!txt) return "";
    return txt.replace(/(?:l)/g, "r").replace(/(?:L)/g, "R").replace(/cute/ig, "kawaii").replace(/wife/ig, "waifu").replace(/husband/ig, "husbando");
};
export { __default14 as owoify };
export { __default15 as weebify };
const mod = {
    capitalize,
    getRandom,
    reverseString,
    owoify: __default14,
    weebify: __default15,
    generateEmail,
    generateCharacter,
    generateName,
    generateFantasyName,
    generateRace,
    generateString,
    generateChainMail,
    generateStory
};
export { mod as default };
