export default [
  {
    name: "imp",
    plural: "imps",
    level: "lower",
    affiliation: -1,
    intelligence: 3,
    size: 1,
    body_parts: {
      tail: true,
      head: true,
      wings: true,
      hands: true,
      legs: true,
      fingers: true,
      toes: true,
      horns: true,
      animal_ears: false,
    },
    magical: true,
    appearance: 1,
  },
  {
    name: "fairy",
    plural: "faries",
    level: 3,
    affiliation: 1,
    intelligence: 5,
    size: 1,
    body_parts: {
      tail: false,
      head: true,
      wings: true,
      hands: true,
      legs: true,
      fingers: true,
      toes: true,
      horns: false,
      animal_ears: false,
    },
    magical: true,
    appearance: 6,
  },
  {
    name: "dragon",
    plural: "dragons",
    level: 7,
    affiliation: 0,
    intelligence: 7,
    size: 5,
    body_parts: {
      tail: true,
      head: true,
      wings: true,
      hands: true,
      legs: true,
      fingers: true,
      toes: true,
      horns: true,
      animal_ears: true,
    },
    magical: true,
    appearance: 5,
  },
  {
    name: "elf",
    plural: "elves",
    level: 5,
    affiliation: 0,
    intelligence: 5,
    size: 3,
    body_parts: {
      tail: false,
      head: true,
      wings: false,
      hands: true,
      legs: true,
      fingers: true,
      toes: true,
      horns: false,
      animal_ears: true,
    },
    magical: true,
    appearance: 6,
  },
  {
    name: "angel",
    plural: "angels",
    level: 7,
    affiliation: 1,
    intelligence: 7,
    size: 3,
    body_parts: {
      tail: false,
      head: true,
      wings: true,
      hands: true,
      legs: true,
      fingers: true,
      toes: true,
      horns: false,
      animal_ears: false,
    },
    magical: true,
    appearance: 7,
  },
  {
    name: "giant",
    plural: "giants",
    level: 5,
    affiliation: 0,
    intelligence: 3,
    size: 5,
    body_parts: {
      tail: false,
      head: true,
      wings: false,
      hands: true,
      legs: true,
      fingers: true,
      toes: true,
      horns: true,
      animal_ears: false,
    },
    magical: true,
    appearance: 1,
  },
  {
    name: "skeleton",
    plural: "skeletons",
    level: 1,
    affiliation: -1,
    intelligence: 0,
    size: 3,
    body_parts: {
      tail: false,
      head: false,
      wings: false,
      hands: false,
      legs: false,
      fingers: false,
      toes: false,
      horns: false,
      animal_ears: false,
    },
    magical: false,
    appearance: 0,
  },
  {
    name: "undead",
    plural: "undead",
    level: 1,
    affiliation: -1,
    intelligence: 0,
    size: 3,
    body_parts: {
      tail: false,
      head: true,
      wings: false,
      hands: true,
      legs: true,
      fingers: true,
      toes: true,
      horns: false,
      animal_ears: false,
    },
    magical: false,
    appearance: 0,
  },
  {
    name: "succubus",
    plural: "succubi",
    level: 3,
    affiliation: -1,
    intelligence: 5,
    size: 3,
    body_parts: {
      tail: true,
      head: true,
      wings: true,
      hands: true,
      legs: true,
      fingers: true,
      toes: true,
      horns: true,
      animal_ears: false,
    },
    magical: true,
    appearance: 6,
  },
  {
    name: "incubus",
    plural: "incubi",
    level: 3,
    affiliation: -1,
    intelligence: 5,
    size: 3,
    body_parts: {
      tail: true,
      head: true,
      wings: true,
      hands: true,
      legs: true,
      fingers: true,
      toes: true,
      horns: true,
      animal_ears: false,
    },
    magical: true,
    appearance: 6,
  },
  {
    name: "demon",
    plural: "demons",
    level: 3,
    affiliation: -1,
    intelligence: 3,
    size: 3,
    body_parts: {
      tail: true,
      head: true,
      wings: true,
      hands: true,
      legs: true,
      fingers: true,
      toes: true,
      horns: true,
      animal_ears: true,
    },
    magical: true,
    appearance: 3,
  },
  {
    name: "slime",
    plural: "slimes",
    level: 1,
    affiliation: -1,
    intelligence: 3,
    size: 1,
    body_parts: {
      tail: true,
      head: true,
      wings: true,
      hands: true,
      legs: true,
      fingers: true,
      toes: true,
      horns: true,
      animal_ears: true,
    },
    magical: true,
    appearance: "disputable",
  },
  {
    name: "wisp",
    plural: "wisps",
    level: 1,
    affiliation: 0,
    intelligence: 0,
    size: 1,
    body_parts: {
      tail: false,
      head: false,
      wings: false,
      hands: false,
      legs: false,
      fingers: false,
      toes: false,
      horns: false,
      animal_ears: false,
    },
    magical: true,
    appearance: "disputable",
  },
  {
    name: "harpy",
    plural: "harpies",
    level: 1,
    affiliation: 0,
    intelligence: 3,
    size: 3,
    body_parts: {
      tail: true,
      head: true,
      wings: true,
      hands: false,
      legs: true,
      fingers: false,
      toes: true,
      horns: false,
      animal_ears: false,
    },
    magical: false,
    appearance: 3,
  },
  {
    name: "bat",
    plural: "bats",
    level: 1,
    affiliation: 0,
    intelligence: 1,
    size: "tiny",
    body_parts: {
      tail: true,
      head: true,
      wings: true,
      hands: false,
      legs: true,
      fingers: false,
      toes: true,
      horns: false,
      animal_ears: true,
    },
    magical: false,
    appearance: 1,
  },
  {
    name: "orc",
    plural: "orcs",
    level: 3,
    affiliation: -1,
    intelligence: 3,
    size: 4,
    body_parts: {
      tail: true,
      head: true,
      wings: false,
      hands: true,
      legs: true,
      fingers: true,
      toes: true,
      horns: true,
      animal_ears: true,
    },
    magical: false,
    appearance: 1,
  },
  {
    name: "goblin",
    plural: "goblins",
    level: 1,
    affiliation: -1,
    intelligence: 3,
    size: 1,
    body_parts: {
      tail: false,
      head: true,
      wings: false,
      hands: true,
      legs: true,
      fingers: true,
      toes: true,
      horns: false,
      animal_ears: false,
    },
    magical: false,
    appearance: 1,
  },
  {
    name: "kobold",
    plural: "kobolds",
    level: 5,
    affiliation: 0,
    intelligence: 3,
    size: 4,
    body_parts: {
      tail: true,
      head: true,
      wings: false,
      hands: true,
      legs: true,
      fingers: true,
      toes: true,
      horns: false,
      animal_ears: true,
    },
    magical: false,
    appearance: 1,
  },
  {
    name: "dark elf",
    plural: "dark elves",
    level: 5,
    affiliation: -1,
    intelligence: 5,
    size: 3,
    body_parts: {
      tail: false,
      head: true,
      wings: false,
      hands: true,
      legs: true,
      fingers: true,
      toes: true,
      horns: false,
      animal_ears: false,
    },
    magical: true,
    appearance: 6,
  },
  {
    name: "golem",
    plural: "golems",
    level: 5,
    affiliation: 0,
    intelligence: 1,
    size: "disputable",
    body_parts: {
      tail: true,
      head: true,
      wings: false,
      hands: true,
      legs: true,
      fingers: true,
      toes: true,
      horns: true,
      animal_ears: false,
    },
    magical: true,
    appearance: "disputable",
  },
  {
    name: "dragonewt",
    plural: "dragonewts",
    level: 5,
    affiliation: 0,
    intelligence: 5,
    size: 3,
    body_parts: {
      tail: true,
      head: true,
      wings: true,
      hands: true,
      legs: true,
      fingers: true,
      toes: true,
      horns: true,
      animal_ears: true,
    },
    magical: false,
    appearance: 5,
  },
  {
    name: "sandworm",
    plural: "sandworms",
    level: 6,
    affiliation: -1,
    intelligence: 0,
    size: 5,
    body_parts: {
      tail: false,
      head: false,
      wings: false,
      hands: false,
      legs: false,
      fingers: false,
      toes: false,
      horns: false,
      animal_ears: false,
    },
    magical: false,
    appearance: 1,
  },
  {
    name: "werewolf",
    plural: "werewolves",
    level: 3,
    affiliation: 0,
    intelligence: 3,
    size: 4,
    body_parts: {
      tail: true,
      head: true,
      wings: false,
      hands: true,
      legs: true,
      fingers: true,
      toes: true,
      horns: false,
      animal_ears: true,
    },
    magical: false,
    appearance: 3,
  },
  {
    name: "vampire",
    plural: "vampires",
    level: 5,
    affiliation: -1,
    intelligence: 5,
    size: 3,
    body_parts: {
      tail: false,
      head: true,
      wings: true,
      hands: true,
      legs: true,
      fingers: true,
      toes: true,
      horns: false,
      animal_ears: false,
    },
    magical: false,
    appearance: 5,
  },
  {
    name: "lamia",
    plural: "lamia",
    level: 1,
    affiliation: -1,
    intelligence: 3,
    size: 3,
    body_parts: {
      tail: true,
      head: true,
      wings: false,
      hands: true,
      legs: false,
      fingers: true,
      toes: false,
      horns: false,
      animal_ears: false,
    },
    magical: false,
    appearance: 5,
  },
  {
    name: "ogre",
    plural: "ogres",
    level: 3,
    affiliation: -1,
    intelligence: 3,
    size: 4,
    body_parts: {
      tail: false,
      head: true,
      wings: false,
      hands: true,
      legs: true,
      fingers: true,
      toes: true,
      horns: true,
      animal_ears: false,
    },
    magical: false,
    appearance: 1,
  },
  {
    name: "oni",
    plural: "oni",
    level: 3,
    affiliation: -1,
    intelligence: 3,
    size: 4,
    body_parts: {
      tail: false,
      head: true,
      wings: false,
      hands: true,
      legs: true,
      fingers: true,
      toes: true,
      horns: true,
      animal_ears: false,
    },
    magical: false,
    appearance: 1,
  },
  {
    name: "siren",
    plural: "sirens",
    level: 3,
    affiliation: -1,
    intelligence: 3,
    size: 3,
    body_parts: {
      tail: true,
      head: true,
      wings: false,
      hands: true,
      legs: false,
      fingers: true,
      toes: true,
      horns: false,
      animal_ears: false,
    },
    magical: true,
    appearance: 5,
  },
  {
    name: "griffon",
    plural: "griffons",
    level: 5,
    affiliation: 1,
    intelligence: 5,
    size: 4,
    body_parts: {
      tail: true,
      head: true,
      wings: true,
      hands: true,
      legs: true,
      fingers: true,
      toes: true,
      horns: true,
      animal_ears: true,
    },
    magical: false,
    appearance: 5,
  },
  {
    name: "manticore",
    plural: "manticores",
    level: 5,
    affiliation: -1,
    intelligence: 3,
    size: 4,
    body_parts: {
      tail: true,
      head: true,
      wings: true,
      hands: true,
      legs: true,
      fingers: true,
      toes: true,
      horns: true,
      animal_ears: true,
    },
    magical: false,
    appearance: 1,
  },
  {
    name: "hippogriff",
    plural: "hippogriff",
    level: 5,
    affiliation: 1,
    intelligence: 5,
    size: 4,
    body_parts: {
      tail: true,
      head: true,
      wings: true,
      hands: true,
      legs: true,
      fingers: true,
      toes: true,
      horns: true,
      animal_ears: true,
    },
    magical: false,
    appearance: 1,
  },
  {
    name: "drake",
    plural: "drakes",
    level: 5,
    affiliation: 0,
    intelligence: 5,
    size: 5,
    body_parts: {
      tail: true,
      head: true,
      wings: false,
      hands: true,
      legs: true,
      fingers: true,
      toes: true,
      horns: true,
      animal_ears: true,
    },
    magical: true,
    appearance: 5,
  },
  {
    name: "wyvern",
    plural: "wyverns",
    level: 3,
    affiliation: -1,
    intelligence: 1,
    size: 4,
    body_parts: {
      tail: true,
      head: true,
      wings: true,
      hands: false,
      legs: false,
      fingers: false,
      toes: false,
      horns: true,
      animal_ears: true,
    },
    magical: false,
    appearance: 1,
  },
  {
    name: "wraith",
    plural: "wraiths",
    level: 3,
    affiliation: -1,
    intelligence: 1,
    size: 3,
    body_parts: {
      tail: false,
      head: false,
      wings: false,
      hands: false,
      legs: false,
      fingers: false,
      toes: false,
      horns: false,
      animal_ears: false,
    },
    magical: true,
    appearance: 1,
  },
  {
    name: "gashadokuro",
    plural: "gashadokuro",
    level: 5,
    affiliation: -1,
    intelligence: 1,
    size: 5,
    body_parts: {
      tail: true,
      head: true,
      wings: false,
      hands: true,
      legs: true,
      fingers: true,
      toes: true,
      horns: false,
      animal_ears: false,
    },
    magical: true,
    appearance: 1,
  },
  {
    name: "lich",
    plural: "lich",
    level: 5,
    affiliation: -1,
    intelligence: 5,
    size: 3,
    body_parts: {
      tail: false,
      head: true,
      wings: false,
      hands: true,
      legs: true,
      fingers: true,
      toes: true,
      horns: false,
      animal_ears: false,
    },
    magical: true,
    appearance: 1,
  },
  {
    name: "monstrous mushroom",
    plural: "monstrous mushrooms",
    level: 3,
    affiliation: -1,
    intelligence: 5,
    size: 3,
    body_parts: {
      tail: false,
      head: true,
      wings: false,
      hands: true,
      legs: true,
      fingers: true,
      toes: true,
      horns: false,
      animal_ears: false,
    },
    magical: false,
    appearance: 1,
  },
  {
    name: "mycelium",
    plural: "mycelium",
    level: 1,
    affiliation: -1,
    intelligence: 3,
    size: 1,
    body_parts: {
      tail: false,
      head: true,
      wings: false,
      hands: false,
      legs: false,
      fingers: false,
      toes: false,
      horns: false,
      animal_ears: false,
    },
    magical: false,
    appearance: 1,
  },
];
