export default [
  {
    "name": "cat",
    "plural": "cats",
    "level": 1,
    "affiliation": 0,
    "intelligence": 1,
    "size": 1,
    "body_parts": {
      "tail": true,
      "head": true,
      "wings": false,
      "hands": true,
      "legs": true,
      "fingers": true,
      "toes": true,
      "horns": false,
      "animal_ears": true
    },
    "magical": false,
    "appearance": 3
  },
  {
      "name": "kitten",
      "plural": "kittens",
      "level": 1,
      "affiliation": 0,
      "intelligence": 1,
      "size": 1,
      "body_parts": {
        "tail": true,
        "head": true,
        "wings": false,
        "hands": true,
        "legs": true,
        "fingers": true,
        "toes": true,
        "horns": false,
        "animal_ears": true
      },
      "magical": false,
      "appearance": 3
    },
    {
      "name": "watermelon",
      "plural": "watermelons",
      "level": 1,
      "affiliation": 0,
      "intelligence": 1,
      "size": 1,
      "body_parts": {
        "tail": false,
        "head": false,
        "wings": false,
        "hands": false,
        "legs": false,
        "fingers": false,
        "toes": false,
        "horns": false,
        "animal_ears": false
      },
      "magical": false,
      "appearance": 3
    },
    {
      "name": "project manager",
      "plural": "project managers",
      "level": 1,
      "affiliation": 0,
      "intelligence": 1,
      "size": 1,
      "body_parts": {
        "tail": false,
        "head": true,
        "wings": false,
        "hands": true,
        "legs": true,
        "fingers": true,
        "toes": true,
        "horns": true,
        "animal_ears": false
      },
      "magical": false,
      "appearance": 3
    },
    {
      "name": "nokia",
      "plural": "nokia",
      "level": 1,
      "affiliation": 0,
      "intelligence": 1,
      "size": 1,
      "body_parts": {
        "tail": false,
        "head": false,
        "wings": false,
        "hands": false,
        "legs": false,
        "fingers": false,
        "toes": false,
        "horns": false,
        "animal_ears": false
      },
      "magical": false,
      "appearance": 3
    },
    {
      "name": "cock",
      "plural": "cocks",
      "level": 1,
      "affiliation": 0,
      "intelligence": 1,
      "size": 1,
      "body_parts": {
        "tail": true,
        "head": true,
        "wings": true,
        "hands": false,
        "legs": true,
        "fingers": false,
        "toes": true,
        "horns": false,
        "animal_ears": true
      },
      "magical": false,
      "appearance": 3
    },
    {
      "name": "chicken",
      "plural": "chickens",
      "level": 1,
      "affiliation": 0,
      "intelligence": 1,
      "size": 1,
      "body_parts": {
        "tail": true,
        "head": true,
        "wings": true,
        "hands": false,
        "legs": true,
        "fingers": false,
        "toes": true,
        "horns": false,
        "animal_ears": false
      },
      "magical": false,
      "appearance": 3
    },
    {
      "name": "sheep",
      "plural": "sheeps",
      "level": 1,
      "affiliation": 0,
      "intelligence": 1,
      "size": 1,
      "body_parts": {
        "tail": true,
        "head": true,
        "wings": false,
        "hands": true,
        "legs": true,
        "fingers": true,
        "toes": true,
        "horns": false,
        "animal_ears": true
      },
      "magical": false,
      "appearance": 3
    },
    {
      "name": "mule",
      "plural": "mules",
      "level": 1,
      "affiliation": 0,
      "intelligence": 1,
      "size": 1,
      "body_parts": {
        "tail": true,
        "head": true,
        "wings": false,
        "hands": true,
        "legs": true,
        "fingers": true,
        "toes": true,
        "horns": false,
        "animal_ears": true
      },
      "magical": false,
      "appearance": 3
    },
    {
      "name": "horse",
      "plural": "horses",
      "level": 1,
      "affiliation": 0,
      "intelligence": 1,
      "size": 1,
      "body_parts": {
        "tail": true,
        "head": true,
        "wings": false,
        "hands": true,
        "legs": true,
        "fingers": true,
        "toes": true,
        "horns": false,
        "animal_ears": true
      },
      "magical": false,
      "appearance": 3
    },
    {
      "name": "grizzly",
      "plural": "grizzlies",
      "level": 1,
      "affiliation": 0,
      "intelligence": 1,
      "size": 1,
      "body_parts": {
        "tail": true,
        "head": true,
        "wings": false,
        "hands": true,
        "legs": true,
        "fingers": true,
        "toes": true,
        "horns": false,
        "animal_ears": true
      },
      "magical": false,
      "appearance": 3
    },
    {
      "name": "leopard",
      "plural": "leopards",
      "level": 1,
      "affiliation": 0,
      "intelligence": 1,
      "size": 1,
      "body_parts": {
        "tail": true,
        "head": true,
        "wings": false,
        "hands": true,
        "legs": true,
        "fingers": true,
        "toes": true,
        "horns": false,
        "animal_ears": true
      },
      "magical": false,
      "appearance": 3
    },
    {
      "name": "spider",
      "plural": "spiders",
      "level": 1,
      "affiliation": 0,
      "intelligence": 1,
      "size": 1,
      "body_parts": {
        "tail": false,
        "head": true,
        "wings": false,
        "hands": false,
        "legs": true,
        "fingers": false,
        "toes": false,
        "horns": false,
        "animal_ears": false
      },
      "magical": false,
      "appearance": 3
    },
    {
      "name": "fly",
      "plural": "flies",
      "level": 1,
      "affiliation": 0,
      "intelligence": 1,
      "size": 1,
      "body_parts": {
        "tail": false,
        "head": true,
        "wings": true,
        "hands": false,
        "legs": true,
        "fingers": false,
        "toes": false,
        "horns": false,
        "animal_ears": false
      },
      "magical": false,
      "appearance": 3
    },
    {
      "name": "crocodile",
      "plural": "crocodiles",
      "level": 1,
      "affiliation": 0,
      "intelligence": 1,
      "size": 1,
      "body_parts": {
        "tail": true,
        "head": true,
        "wings": false,
        "hands": true,
        "legs": true,
        "fingers": true,
        "toes": true,
        "horns": false,
        "animal_ears": false
      },
      "magical": false,
      "appearance": 3
    },
    {
      "name": "gorilla",
      "plural": "gorillas",
      "level": 1,
      "affiliation": 0,
      "intelligence": 1,
      "size": 1,
      "body_parts": {
        "tail": true,
        "head": true,
        "wings": false,
        "hands": true,
        "legs": true,
        "fingers": true,
        "toes": true,
        "horns": false,
        "animal_ears": false
      },
      "magical": false,
      "appearance": 3
    },
    {
      "name": "fox",
      "plural": "foxes",
      "level": 1,
      "affiliation": 0,
      "intelligence": 1,
      "size": 1,
      "body_parts": {
        "tail": true,
        "head": true,
        "wings": false,
        "hands": true,
        "legs": true,
        "fingers": true,
        "toes": true,
        "horns": false,
        "animal_ears": true
      },
      "magical": false,
      "appearance": 3
    },
    {
      "name": "puppy",
      "plural": "puppies",
      "level": 1,
      "affiliation": 0,
      "intelligence": 1,
      "size": 1,
      "body_parts": {
        "tail": true,
        "head": true,
        "wings": false,
        "hands": true,
        "legs": true,
        "fingers": true,
        "toes": true,
        "horns": false,
        "animal_ears": true
      },
      "magical": false,
      "appearance": 3
    },
    {
      "name": "dog",
      "plural": "dogs",
      "level": 1,
      "affiliation": 0,
      "intelligence": 1,
      "size": 1,
      "body_parts": {
        "tail": true,
        "head": true,
        "wings": false,
        "hands": true,
        "legs": true,
        "fingers": true,
        "toes": true,
        "horns": false,
        "animal_ears": true
      },
      "magical": false,
      "appearance": 3
    },
    {
      "name": "chimpanzee",
      "plural": "chimpanzees",
      "level": 1,
      "affiliation": 0,
      "intelligence": 3,
      "size": 1,
      "body_parts": {
        "tail": true,
        "head": true,
        "wings": false,
        "hands": true,
        "legs": true,
        "fingers": true,
        "toes": true,
        "horns": false,
        "animal_ears": false
      },
      "magical": false,
      "appearance": 3
    },
    {
      "name": "polar bear",
      "plural": "polar bears",
      "level": 1,
      "affiliation": 0,
      "intelligence": 1,
      "size": 1,
      "body_parts": {
        "tail": true,
        "head": true,
        "wings": false,
        "hands": true,
        "legs": true,
        "fingers": true,
        "toes": true,
        "horns": false,
        "animal_ears": true
      },
      "magical": false,
      "appearance": 3
    },
    {
      "name": "wolf",
      "plural": "wolves",
      "level": 1,
      "affiliation": 0,
      "intelligence": 1,
      "size": 1,
      "body_parts": {
        "tail": true,
        "head": true,
        "wings": false,
        "hands": true,
        "legs": true,
        "fingers": true,
        "toes": true,
        "horns": false,
        "animal_ears": true
      },
      "magical": false,
      "appearance": 3
    },
    {
      "name": "snake",
      "plural": "snakes",
      "level": 1,
      "affiliation": 0,
      "intelligence": 1,
      "size": 1,
      "body_parts": {
        "tail": true,
        "head": true,
        "wings": false,
        "hands": false,
        "legs": false,
        "fingers": false,
        "toes": false,
        "horns": false,
        "animal_ears": false
      },
      "magical": false,
      "appearance": 3
    },
    {
      "name": "ant",
      "plural": "ants",
      "level": 1,
      "affiliation": 0,
      "intelligence": 1,
      "size": 1,
      "body_parts": {
        "tail": true,
        "head": true,
        "wings": false,
        "hands": true,
        "legs": true,
        "fingers": true,
        "toes": true,
        "horns": false,
        "animal_ears": false
      },
      "magical": false,
      "appearance": 3
    },
    {
      "name": "serial killer",
      "plural": "serial killers",
      "level": 1,
      "affiliation": 0,
      "intelligence": 1,
      "size": 1,
      "body_parts": {
        "tail": false,
        "head": true,
        "wings": false,
        "hands": true,
        "legs": true,
        "fingers": true,
        "toes": true,
        "horns": false,
        "animal_ears": false
      },
      "magical": false,
      "appearance": 3
    },
    {
      "name": "catfood",
      "plural": "catfood",
      "level": 1,
      "affiliation": 0,
      "intelligence": 1,
      "size": 1,
      "body_parts": {
        "tail": false,
        "head": false,
        "wings": false,
        "hands": false,
        "legs": false,
        "fingers": false,
        "toes": false,
        "horns": false,
        "animal_ears": false
      },
      "magical": false,
      "appearance": 3
    },
    {
      "name": "pumpkin",
      "plural": "pumpkins",
      "level": 1,
      "affiliation": 0,
      "intelligence": 1,
      "size": 1,
      "body_parts": {
        "tail": false,
        "head": true,
        "wings": false,
        "hands": false,
        "legs": false,
        "fingers": false,
        "toes": false,
        "horns": false,
        "animal_ears": false
      },
      "magical": false,
      "appearance": 3
    },
    {
      "name": "spider",
      "plural": "spiders",
      "level": 1,
      "affiliation": 0,
      "intelligence": 1,
      "size": 1,
      "body_parts": {
        "tail": false,
        "head": true,
        "wings": false,
        "hands": false,
        "legs": true,
        "fingers": false,
        "toes": false,
        "horns": false,
        "animal_ears": false
      },
      "magical": false,
      "appearance": 3
    },
    {
      "name": "centipede",
      "plural": "centipedes",
      "level": 1,
      "affiliation": 0,
      "intelligence": 1,
      "size": 1,
      "body_parts": {
        "tail": true,
        "head": true,
        "wings": false,
        "hands": false,
        "legs": true,
        "fingers": false,
        "toes": false,
        "horns": false,
        "animal_ears": false
      },
      "magical": false,
      "appearance": 3
    },
    {
      "name": "clown",
      "plural": "clowns",
      "level": 1,
      "affiliation": 0,
      "intelligence": 1,
      "size": 1,
      "body_parts": {
        "tail": false,
        "head": true,
        "wings": false,
        "hands": true,
        "legs": true,
        "fingers": true,
        "toes": true,
        "horns": false,
        "animal_ears": false
      },
      "magical": false,
      "appearance": 3
    },
    {
      "name": "godzilla",
      "plural": "godzillas",
      "level": 1,
      "affiliation": 0,
      "intelligence": 1,
      "size": 1,
      "body_parts": {
        "tail": true,
        "head": true,
        "wings": false,
        "hands": true,
        "legs": true,
        "fingers": true,
        "toes": true,
        "horns": false,
        "animal_ears": true
      },
      "magical": false,
      "appearance": 3
    },
    {
      "name": "villager",
      "plural": "villagers",
      "level": 1,
      "affiliation": 0,
      "intelligence": 1,
      "size": 1,
      "body_parts": {
        "tail": false,
        "head": true,
        "wings": false,
        "hands": true,
        "legs": true,
        "fingers": true,
        "toes": true,
        "horns": false,
        "animal_ears": false
      },
      "magical": false,
      "appearance": 3
    },
    {
      "name": "yakuza",
      "plural": "yakuza",
      "level": 1,
      "affiliation": 0,
      "intelligence": 1,
      "size": 1,
      "body_parts": {
        "tail": false,
        "head": true,
        "wings": false,
        "hands": true,
        "legs": true,
        "fingers": true,
        "toes": true,
        "horns": false,
        "animal_ears": false
      },
      "magical": false,
      "appearance": 3
    },
    {
      "name": "lion",
      "plural": "lions",
      "level": 1,
      "affiliation": 0,
      "intelligence": 1,
      "size": 1,
      "body_parts": {
        "tail": true,
        "head": true,
        "wings": false,
        "hands": true,
        "legs": true,
        "fingers": true,
        "toes": true,
        "horns": false,
        "animal_ears": true
      },
      "magical": false,
      "appearance": 3
    }
]