import getRandom from '../../util/getRandom.js';

const thirdperson = [
  "hero",
  "mage",
  "wizard",
  "sage",
  "monk",
  "NEET",
  "dragon",
  "hunter",
  "salesman",
  "salaryman",
  "digital artist",
  "weeb",
  "artist",
  "gacha gamer",
  "game developer",
  "Florida man",
  "pokemon master",
  "narcissist",
  "programmer",
  "web developer",
  "yankee",
  "yakuza",
  "ying-yang master",
  "taoist",
  "archangel",
  "baiter",
  "investigator",
  "king",
  "magician",
  "eggman",
  "lancer",
  "archer",
  "berserker",
  "rider",
  "athlete",
  "master",
  "martial artist",
  "demon",
  "god",
  "zombie",
  "skeleton",
  "vampire",
  "undead",
  "lich",
  "golem",
  "swordsman",
  "sword saint",
  "shielder",
  "spearmaster",
  "gunslinger",
  "cowboy",
  "karen",
  "tomboy",
  "femboy",
  "gal",
  "nerd",
];

const questions = ["if", "do", "did", "what if", "but then", "and"];

const adjectives = [
  "Chinese",
  "Indian",
  "Japanese",
  "Russian",
  "German",
  "accurate",
  "adventurous",
  "aggressive",
  "agoraphobic",
  "alien",
  "alpha",
  "amazing",
  "ancient",
  "angelic",
  "average",
  "avian",
  "awesome",
  "bad",
  "beefy",
  "belligerent",
  "betrayed",
  "bipedal",
  "bitter",
  "black",
  "blind",
  "boisterous",
  "brilliant",
  "bronze",
  "canine",
  "certified",
  "charitable",
  "charming",
  "cheeky",
  "cheerful",
  "childish",
  "chivalrous",
  "clever",
  "clueless",
  "clumsy",
  "comical",
  "complex",
  "confident",
  "cool",
  "crybaby",
  "cuddly",
  "cunning",
  "curious",
  "cute",
  "dangerous",
  "dark",
  "decent",
  "delicious",
  "delusional",
  "dense",
  "desperate",
  "diabetic",
  "divine",
  "dominant",
  "dragon",
  "dramatic",
  "drunk",
  "dwarven",
  "eerie",
  "egghead",
  "electric",
  "elegant",
  "elemental",
  "elven",
  "enchanting",
  "faithful",
  "famous",
  "fantastic",
  "feline",
  "female",
  "feminine",
  "friendly",
  "funny",
  "gallant",
  "gay",
  "generous",
  "gentle",
  "geographic",
  "giant",
  "godlike",
  "gold",
  "good",
  "grand",
  "great",
  "gruesome",
  "gullible",
  "harsh",
  "high",
  "holy",
  "hostile",
  "humble",
  "hypersonic",
  "idiotic",
  "immortal",
  "inferior",
  "innocent",
  "invincible",
  "iron",
  "jazzy",
  "jinxed",
  "jittery",
  "kidney-shaped",
  "kindhearted",
  "lackadaisical",
  "lackluster",
  "large",
  "lawful",
  "legendary",
  "lemon-like",
  "listless",
  "lively",
  "lowly",
  "malnourished",
  "masculine",
  "massive",
  "matchless",
  "meek",
  "merciless",
  "mindless",
  "monstrous",
  "mythical",
  "naive",
  "naked",
  "nerdy",
  "noble",
  "nocturnal",
  "notorious",
  "novel",
  "obsessive",
  "omnipotent",
  "omniscient",
  "optimistic",
  "outstanding",
  "overpowered",
  "overweight",
  "peaceful",
  "pessimistic",
  "popular",
  "powerful",
  "powerless",
  "pretty",
  "proud",
  "pure",
  "rabid",
  "reincarnated",
  "repugnant",
  "repulsive",
  "rich",
  "rotten",
  "round",
  "rowdy",
  "royal",
  "rude",
  "rugged",
  "ruthless",
  "sacred",
  "sassy",
  "selfish",
  "selfless",
  "shiny",
  "short",
  "silver",
  "skinny",
  "spirit",
  "steel",
  "stereotypical",
  "strong",
  "successful",
  "summoned",
  "super",
  "sweet",
  "talkative",
  "tall",
  "timid",
  "tiny",
  "trashy",
  "tyrannical",
  "ultimate",
  "underweight",
  "unmatched",
  "upbeat",
  "valiant",
  "verbose",
  "villainous",
  "viscous",
  "voracious",
  "warlord",
  "weak",
  "weary",
  "wheezy",
  "whiny",
  "wholesome",
  "wicked",
  "wise",
  "witty",
  "world-class",
  "xenophobic",
  "young",
  "zazzy",
  "zen",
];

const level = ["level", "lv", "lvl", "tier", "stage", "rank", "class"];
const levels = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 20, 30, 40, 50, 60, 69, 70, 80, 90, 99, 100, 101, 200, 420, 500, 666, 999, 1000, 9999, 10000, 99999, 100000, 1000000]

/*
export default () => {
  const person = Math.ceil(Math.random() * 3);
  return `${
    person === 1
      ? "I"
      : person === 2
      ? `${
          Math.random() < 0.5
            ? `${capitalize(getRandom(questions))} you`
            : "You"
        }`
      : `The ${
          Math.random() < 0.5
            ? Math.random() < 0.5
              ? `${getRandom(adjectives)} `
              : `${getRandom(level)} ${getRandom(levels)} `
            : ""
        }${getRandom(thirdperson)}`
  }`;
};
*/

export default () => {
  return `${
    Math.random() < 0.9
      ? Math.random() > 0.3
        ? `${getRandom(adjectives)} `
        : `${getRandom(level)} ${getRandom(levels)} `
      : ""
  }${getRandom(thirdperson)}`
}